let PIECTRL_REGISTERS = [
	{ name: "PIECTRL", description: "PIE Control Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	ENPIE", description: "PIE Block", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	PIEVECT", description: "Vector Address", size: "15", shift: "1", mask: "0xFFFE" },
		]
	},
	{ name: "PIEACK", description: "PIE Acknowledge Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	ACK1", description: "PIE Interrupt Group 1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	ACK2", description: "PIE Interrupt Group 2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	ACK3", description: "PIE Interrupt Group 3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	ACK4", description: "PIE Interrupt Group 4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	ACK5", description: "PIE Interrupt Group 5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	ACK6", description: "PIE Interrupt Group 6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	ACK7", description: "PIE Interrupt Group 7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	ACK8", description: "PIE Interrupt Group 8", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	ACK9", description: "PIE Interrupt Group 9", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	ACK10", description: "PIE Interrupt Group 10", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	ACK11", description: "PIE Interrupt Group 11", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	ACK12", description: "PIE Interrupt Group 12", size: "1", shift: "11", mask: "0x800" },
		]
	},
	{ name: "PIEIER1", description: "PIE INT1 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR1", description: "PIE INT1 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER2", description: "PIE INT2 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR2", description: "PIE INT2 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER3", description: "PIE INT3 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR3", description: "PIE INT3 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER4", description: "PIE INT4 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR4", description: "PIE INT4 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER5", description: "PIE INT5 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR5", description: "PIE INT5 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER6", description: "PIE INT6 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR6", description: "PIE INT6 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER7", description: "PIE INT7 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR7", description: "PIE INT7 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER8", description: "PIE INT8 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR8", description: "PIE INT8 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER9", description: "PIE INT9 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR9", description: "PIE INT9 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER10", description: "PIE INT10 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR10", description: "PIE INT10 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER11", description: "PIE INT11 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR11", description: "PIE INT11 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER12", description: "PIE INT12 IER Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR12", description: "PIE INT12 IFR Register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	INTx1", description: "0	INTx1", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	INTx2", description: "1	INTx2", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	INTx3", description: "2	INTx3", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	INTx4", description: "3	INTx4", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	INTx5", description: "4	INTx5", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	INTx6", description: "5	INTx6", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	INTx7", description: "6	INTx7", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	INTx8", description: "7	INTx8", size: "1", shift: "7", mask: "0x80" },
		]
	},
];
module.exports = {
	piectrlRegisters: PIECTRL_REGISTERS,
}
