let MCBSP_REGISTERS = [
	{ name: "DRR2", description: "Data receive register bits 31-16", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	HWLB", description: "word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "Uint16	HWHB", description: "word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DRR1", description: "Data receive register bits 15-0", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	LWLB", description: "word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "Uint16	LWHB", description: "word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DXR2", description: "Data transmit register bits 31-16", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	HWLB", description: "word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "Uint16	HWHB", description: "word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DXR1", description: "Data transmit register bits 15-0", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	LWLB", description: "word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "Uint16	LWHB", description: "word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "SPCR2", description: "Control register 2", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XRST", description: "reset", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XRDY", description: "ready", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XEMPTY", description: "empty", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XSYNCERR", description: "sync error INT flag", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XINTM", description: "Interupt mode bits", size: "2", shift: "4", mask: "0x30" },
			{ name: "Uint16	GRST", description: "rate generator reset", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	FRST", description: "sync logic reset", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	SOFT", description: "bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	FREE", description: "bit", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "SPCR1", description: "Control register 1", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RRST", description: "reset", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RRDY", description: "ready", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RFULL", description: "full", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RSYNCERR", description: "sync error INT flag", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RINTM", description: "Interupt mode bits", size: "2", shift: "4", mask: "0x30" },
			{ name: "Uint16	DXENA", description: "delay enable", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	CLKSTP", description: "stop mode", size: "2", shift: "11", mask: "0x1800" },
			{ name: "Uint16	RJUST", description: "sign extension and justification mode", size: "2", shift: "13", mask: "0x6000" },
			{ name: "Uint16	DLB", description: "loopback", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCR2", description: "Receive Control register 2", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RDATDLY", description: "Receive data delay", size: "2", shift: "0", mask: "0x3" },
			{ name: "Uint16	RFIG", description: "frame sync ignore", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCOMPAND", description: "Companding Mode selects", size: "2", shift: "3", mask: "0x18" },
			{ name: "Uint16	RWDLEN2", description: "word length 2", size: "3", shift: "5", mask: "0xE0" },
			{ name: "Uint16	RFRLEN2", description: "Frame length 2", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "Uint16	RPHASE", description: "Phase", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCR1", description: "Receive Control register 1", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RWDLEN1", description: "word length 1", size: "3", shift: "5", mask: "0xE0" },
			{ name: "Uint16	RFRLEN1", description: "Receive Frame length 1", size: "7", shift: "8", mask: "0x7F00" },
		]
	},
	{ name: "XCR2", description: "Transmit Control register 2", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XDATDLY", description: "Transmit data delay", size: "2", shift: "0", mask: "0x3" },
			{ name: "Uint16	XFIG", description: "frame sync ignore", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCOMPAND", description: "Companding Mode selects", size: "2", shift: "3", mask: "0x18" },
			{ name: "Uint16	XWDLEN2", description: "word length 2", size: "3", shift: "5", mask: "0xE0" },
			{ name: "Uint16	XFRLEN2", description: "Frame length 2", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "Uint16	XPHASE", description: "Phase", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCR1", description: "Transmit Control register 1", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XWDLEN1", description: "word length 1", size: "3", shift: "5", mask: "0xE0" },
			{ name: "Uint16	XFRLEN1", description: "Transmit Frame length 1", size: "7", shift: "8", mask: "0x7F00" },
		]
	},
	{ name: "SRGR2", description: "Sample rate generator register 2", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	FPER", description: "Frame-sync period", size: "12", shift: "0", mask: "0xFFF" },
			{ name: "Uint16	FSGM", description: "sync generator mode", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	CLKSM", description: "rate generator mode", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	GSYNC", description: "sync", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "SRGR1", description: "Sample rate generator register 1", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	CLKGDV", description: "divider", size: "8", shift: "0", mask: "0xFF" },
			{ name: "Uint16	FWID", description: "width", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "MCR2", description: "Multi-channel register 2", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XMCM", description: "multichannel mode", size: "2", shift: "0", mask: "0x3" },
			{ name: "Uint16	XCBLK", description: "current block", size: "3", shift: "2", mask: "0x1C" },
			{ name: "Uint16	XPABLK", description: "partition A Block", size: "2", shift: "5", mask: "0x60" },
			{ name: "Uint16	XPBBLK", description: "partition B Block", size: "2", shift: "7", mask: "0x180" },
			{ name: "Uint16	XMCME", description: "multi-channel enhance mode", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "MCR1", description: "Multi-channel register 1", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RMCM", description: "multichannel mode", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCBLK", description: "current block", size: "3", shift: "2", mask: "0x1C" },
			{ name: "Uint16	RPABLK", description: "partition A Block", size: "2", shift: "5", mask: "0x60" },
			{ name: "Uint16	RPBBLK", description: "partition B Block", size: "2", shift: "7", mask: "0x180" },
			{ name: "Uint16	RMCME", description: "multi-channel enhance mode", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "RCERA", description: "Receive channel enable partition A", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEA0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEA1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEA2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEA3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEA4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEA5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEA6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEA7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEA8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEA9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEA10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEA11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEA12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEA13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEA14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEA15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERB", description: "Receive channel enable partition B", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEB0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEB1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEB2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEB3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEB4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEB5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEB6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEB7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEB8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEB9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEB10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEB11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEB12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEB13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEB14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEB15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERA", description: "Transmit channel enable partition A", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERA0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERA1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERA2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERA3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERA4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERA5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERA6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERA7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERA8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERA9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERA10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERA11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERA12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERA13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERA14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERA15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERB", description: "Transmit channel enable partition B", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERB0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERB1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERB2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERB3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERB4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERB5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERB6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERB7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERB8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERB9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERB10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERB11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERB12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERB13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERB14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERB15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "PCR", description: "Pin Control register", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	CLKRP", description: "Clock polarity", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	CLKXP", description: "clock polarity", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	FSRP", description: "Frame synchronization polarity", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	FSXP", description: "Frame synchronization polarity", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	SCLKME", description: "clock mode selection", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	CLKRM", description: "Clock Mode", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	CLKXM", description: "Clock Mode.", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	FSRM", description: "Frame Synchronization Mode", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	FSXM", description: "Frame Synchronization Mode", size: "1", shift: "11", mask: "0x800" },
		]
	},
	{ name: "RCERC", description: "Receive channel enable partition C", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEC0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEC1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEC2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEC3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEC4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEC5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEC6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEC7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEC8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEC9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEC10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEC11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEC12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEC13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEC14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEC15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERD", description: "Receive channel enable partition D", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCED0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCED1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCED2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCED3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCED4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCED5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCED6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCED7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCED8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCED9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCED10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCED11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCED12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCED13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCED14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCED15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERC", description: "Transmit channel enable partition C", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERC0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERC1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERC2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERC3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERC4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERC5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERC6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERC7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERC8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERC9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERC10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERC11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERC12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERC13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERC14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERC15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERD", description: "Transmit channel enable partition D", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERD0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERD1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERD2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERD3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERD4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERD5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERD6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERD7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERD8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERD9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERD10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERD11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERD12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERD13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERD14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERD15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERE", description: "Receive channel enable partition E", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEE0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEE1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEE2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEE3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEE4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEE5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEE6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEE7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEE8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEE9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEE10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEE11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEE12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEE13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEE14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEE15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERF", description: "Receive channel enable partition F", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEF0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEF1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEF2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEF3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEF4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEF5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEF6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEF7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEF8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEF9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEF10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEF11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEF12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEF13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEF14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEF15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERE", description: "Transmit channel enable partition E", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERE0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERE1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERE2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERE3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERE4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERE5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERE6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERE7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERE8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERE9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERE10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERE11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERE12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERE13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERE14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERE15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERF", description: "Transmit channel enable partition F", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERF0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERF1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERF2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERF3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERF4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERF5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERF6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERF7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERF8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERF9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERF10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERF11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERF12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERF13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERF14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERF15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERG", description: "Receive channel enable partition G", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEG0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEG1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEG2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEG3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEG4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEG5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEG6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEG7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEG8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEG9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEG10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEG11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEG12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEG13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEG14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEG15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERH", description: "Receive channel enable partition H", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	RCEH0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RCEH1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	RCEH2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	RCEH3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	RCEH4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	RCEH5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	RCEH6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	RCEH7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	RCEH8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	RCEH9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	RCEH10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	RCEH11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	RCEH12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	RCEH13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	RCEH14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	RCEH15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERG", description: "Transmit channel enable partition G", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERG0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERG1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERG2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERG3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERG4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERG5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERG6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERG7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERG8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERG9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERG10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERG11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERG12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERG13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERG14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERG15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERH", description: "Transmit channel enable partition H", offset: "0x0", size: "0",
		bits: [
			{ name: "Uint16	XCERH0", description: "Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	XCERH1", description: "Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "Uint16	XCERH2", description: "Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "Uint16	XCERH3", description: "Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "Uint16	XCERH4", description: "Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "Uint16	XCERH5", description: "Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "Uint16	XCERH6", description: "Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "Uint16	XCERH7", description: "Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "Uint16	XCERH8", description: "Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "Uint16	XCERH9", description: "Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "Uint16	XCERH10", description: "Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "Uint16	XCERH11", description: "Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "Uint16	XCERH12", description: "Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "Uint16	XCERH13", description: "Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "Uint16	XCERH14", description: "Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "Uint16	XCERH15", description: "Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "MFFINT", description: "Interrupt enable", offset: "0x4", size: "0",
		bits: [
			{ name: "Uint16	XINT", description: "interrupt enable", size: "1", shift: "0", mask: "0x1" },
			{ name: "Uint16	RINT", description: "interrupt enable", size: "1", shift: "2", mask: "0x4" },
		]
	},
];
module.exports = {
	mcbspRegisters: MCBSP_REGISTERS,
}
