let PIECTRL_REGISTERS = [
	{ name: "PIECTRL", description: "PIE control register", offset: "0x0", size: "16",
		bits: [
			{ name: "ENPIE", description: "Enable PIE block", size: "1", shift: "0", mask: "0x1" },
			{ name: "PIEVECT", description: "Fetched vector address", size: "15", shift: "1", mask: "0xFFFE" },
		]
	},
	{ name: "PIEACK", description: "PIE acknowledge", offset: "0x1", size: "16",
		bits: [
			{ name: "ACK1", description: "Acknowledge PIE interrupt group 1", size: "1", shift: "0", mask: "0x1" },
			{ name: "ACK2", description: "Acknowledge PIE interrupt group 2", size: "1", shift: "1", mask: "0x2" },
			{ name: "ACK3", description: "Acknowledge PIE interrupt group 3", size: "1", shift: "2", mask: "0x4" },
			{ name: "ACK4", description: "Acknowledge PIE interrupt group 4", size: "1", shift: "3", mask: "0x8" },
			{ name: "ACK5", description: "Acknowledge PIE interrupt group 5", size: "1", shift: "4", mask: "0x10" },
			{ name: "ACK6", description: "Acknowledge PIE interrupt group 6", size: "1", shift: "5", mask: "0x20" },
			{ name: "ACK7", description: "Acknowledge PIE interrupt group 7", size: "1", shift: "6", mask: "0x40" },
			{ name: "ACK8", description: "Acknowledge PIE interrupt group 8", size: "1", shift: "7", mask: "0x80" },
			{ name: "ACK9", description: "Acknowledge PIE interrupt group 9", size: "1", shift: "8", mask: "0x100" },
			{ name: "ACK10", description: "Acknowledge PIE interrupt group 10", size: "1", shift: "9", mask: "0x200" },
			{ name: "ACK11", description: "Acknowledge PIE interrupt group 11", size: "1", shift: "10", mask: "0x400" },
			{ name: "ACK12", description: "Acknowledge PIE interrupt group 12", size: "1", shift: "11", mask: "0x800" },
		]
	},
	{ name: "PIEIER1", description: "PIE int1 IER register", offset: "0x2", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR1", description: "PIE int1 IFR register", offset: "0x3", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER2", description: "PIE INT2 IER register", offset: "0x4", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR2", description: "PIE INT2 IFR register", offset: "0x5", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER3", description: "PIE INT3 IER register", offset: "0x6", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR3", description: "PIE INT3 IFR register", offset: "0x7", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER4", description: "PIE INT4 IER register", offset: "0x8", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR4", description: "PIE INT4 IFR register", offset: "0x9", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER5", description: "PIE INT5 IER register", offset: "0xA", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR5", description: "PIE INT5 IFR register", offset: "0xB", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER6", description: "PIE INT6 IER register", offset: "0xC", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR6", description: "PIE INT6 IFR register", offset: "0xD", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER7", description: "PIE INT7 IER register", offset: "0xE", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR7", description: "PIE INT7 IFR register", offset: "0xF", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER8", description: "PIE INT8 IER register", offset: "0x10", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR8", description: "PIE INT8 IFR register", offset: "0x11", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER9", description: "PIE INT9 IER register", offset: "0x12", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR9", description: "PIE INT9 IFR register", offset: "0x13", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER10", description: "PIE int10 IER register", offset: "0x14", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR10", description: "PIE int10 IFR register", offset: "0x15", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER11", description: "PIE int11 IER register", offset: "0x16", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR11", description: "PIE int11 IFR register", offset: "0x17", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIER12", description: "PIE int12 IER register", offset: "0x18", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "PIEIFR12", description: "PIE int12 IFR register", offset: "0x19", size: "16",
		bits: [
			{ name: "INTx1", description: "INTx.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTx2", description: "INTx.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTx3", description: "INTx.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTx4", description: "INTx.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTx5", description: "INTx.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTx6", description: "INTx.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTx7", description: "INTx.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTx8", description: "INTx.8", size: "1", shift: "7", mask: "0x80" },
		]
	},
];
module.exports = {
	piectrlRegisters: PIECTRL_REGISTERS,
}
