let MCBSP_REGISTERS = [
	{ name: "DRR2", description: "MCBSP Data receive register bits 31-16", offset: "0x0", size: "16",
		bits: [
			{ name: "HWLB", description: "High word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "HWHB", description: "High word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DRR1", description: "MCBSP Data receive register bits 15-0", offset: "0x1", size: "16",
		bits: [
			{ name: "LWLB", description: "Low word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "LWHB", description: "low word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DXR2", description: "MCBSP Data transmit register bits 31-16", offset: "0x2", size: "16",
		bits: [
			{ name: "HWLB", description: "High word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "HWHB", description: "High word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "DXR1", description: "MCBSP Data transmit register bits 15-0", offset: "0x3", size: "16",
		bits: [
			{ name: "LWLB", description: "Low word low byte", size: "8", shift: "0", mask: "0xFF" },
			{ name: "LWHB", description: "low word high byte", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "SPCR2", description: "MCBSP control register bits 31-16", offset: "0x4", size: "16",
		bits: [
			{ name: "XRST", description: "transmit reset", size: "1", shift: "0", mask: "0x1" },
			{ name: "XRDY", description: "transmit ready", size: "1", shift: "1", mask: "0x2" },
			{ name: "XEMPTY", description: "Transmit empty", size: "1", shift: "2", mask: "0x4" },
			{ name: "XSYNCERR", description: "Transmit syn errorINT flag", size: "1", shift: "3", mask: "0x8" },
			{ name: "XINTM", description: "Transmit interrupt types", size: "2", shift: "4", mask: "0x30" },
			{ name: "GRST", description: "CLKG reset", size: "1", shift: "6", mask: "0x40" },
			{ name: "FRST", description: "Frame sync reset", size: "1", shift: "7", mask: "0x80" },
			{ name: "SOFT", description: "SOFT bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "FREE", description: "FREE bit", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "SPCR1", description: "MCBSP control register bits 15-0", offset: "0x5", size: "16",
		bits: [
			{ name: "RRST", description: "Receive reset", size: "1", shift: "0", mask: "0x1" },
			{ name: "RRDY", description: "Receive  ready", size: "1", shift: "1", mask: "0x2" },
			{ name: "RFULL", description: "Receive  full", size: "1", shift: "2", mask: "0x4" },
			{ name: "RSYNCERR", description: "Receive  syn error", size: "1", shift: "3", mask: "0x8" },
			{ name: "RINTM", description: "Receive  interrupt types", size: "2", shift: "4", mask: "0x30" },
			{ name: "DXENA", description: "DX hi-z enable", size: "1", shift: "7", mask: "0x80" },
			{ name: "CLKSTP", description: "CLKSTOP mode bit", size: "2", shift: "11", mask: "0x1800" },
			{ name: "RJUST", description: "Right justified", size: "2", shift: "13", mask: "0x6000" },
			{ name: "DLB", description: "Digital loop back", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCR2", description: "MCBSP receive control register bits 31-16", offset: "0x6", size: "16",
		bits: [
			{ name: "RDATDLY", description: "Receive data delay", size: "2", shift: "0", mask: "0x3" },
			{ name: "RFIG", description: "Receive  frame sync ignore", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCOMPAND", description: "Receive  Companding Mode selects", size: "2", shift: "3", mask: "0x18" },
			{ name: "RWDLEN2", description: "Receive  word length", size: "3", shift: "5", mask: "0xE0" },
			{ name: "RFRLEN2", description: "Receive  Frame sync", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "RPHASE", description: "Receive Phase", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCR1", description: "MCBSP receive control register bits 15-0", offset: "0x7", size: "16",
		bits: [
			{ name: "RWDLEN1", description: "Receive word length", size: "3", shift: "5", mask: "0xE0" },
			{ name: "RFRLEN1", description: "Receive frame length", size: "7", shift: "8", mask: "0x7F00" },
		]
	},
	{ name: "XCR2", description: "MCBSP transmit control register bits 31-16", offset: "0x8", size: "16",
		bits: [
			{ name: "XDATDLY", description: "Transmit data delay", size: "2", shift: "0", mask: "0x3" },
			{ name: "XFIG", description: "Transmit frame sync ignore", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCOMPAND", description: "Transmit Companding Mode selects", size: "2", shift: "3", mask: "0x18" },
			{ name: "XWDLEN2", description: "Transmit  word length", size: "3", shift: "5", mask: "0xE0" },
			{ name: "XFRLEN2", description: "Transmit  Frame sync", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "XPHASE", description: "Transmit Phase", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCR1", description: "MCBSP transmit control register bits 15-0", offset: "0x9", size: "16",
		bits: [
			{ name: "XWDLEN1", description: "Transmit word length", size: "3", shift: "5", mask: "0xE0" },
			{ name: "XFRLEN1", description: "Transmit frame length", size: "7", shift: "8", mask: "0x7F00" },
		]
	},
	{ name: "SRGR2", description: "MCBSP sample rate gen register bits 31-16", offset: "0xA", size: "16",
		bits: [
			{ name: "FPER", description: "Frame period", size: "12", shift: "0", mask: "0xFFF" },
			{ name: "FSGM", description: "Frame sync generator mode", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CLKSM", description: "Sample rate generator mode", size: "1", shift: "13", mask: "0x2000" },
			{ name: "GSYNC", description: "CLKG sync", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "SRGR1", description: "MCBSP sample rate gen register bits 15-0", offset: "0xB", size: "16",
		bits: [
			{ name: "CLKGDV", description: "CLKG divider", size: "8", shift: "0", mask: "0xFF" },
			{ name: "FWID", description: "Frame width", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "MCR2", description: "MCBSP multichannel register bits 31-16", offset: "0xC", size: "16",
		bits: [
			{ name: "XMCM", description: "Transmit multichannel mode", size: "2", shift: "0", mask: "0x3" },
			{ name: "XCBLK", description: "Transmit current block", size: "3", shift: "2", mask: "0x1C" },
			{ name: "XPABLK", description: "Transmit partition A Block", size: "2", shift: "5", mask: "0x60" },
			{ name: "XPBBLK", description: "Transmit partition B Block", size: "2", shift: "7", mask: "0x180" },
			{ name: "XMCME", description: "Transmit multi-channel enhance mode", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "MCR1", description: "MCBSP multichannel register bits 15-0", offset: "0xD", size: "16",
		bits: [
			{ name: "RMCM", description: "Receive multichannel mode", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCBLK", description: "Receive current block", size: "3", shift: "2", mask: "0x1C" },
			{ name: "RPABLK", description: "Receive partition A Block", size: "2", shift: "5", mask: "0x60" },
			{ name: "RPBBLK", description: "Receive partition B Block", size: "2", shift: "7", mask: "0x180" },
			{ name: "RMCME", description: "Receive multi-channel enhance mode", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "RCERA", description: "MCBSP Receive channel enable partition A", offset: "0xE", size: "16",
		bits: [
			{ name: "RCEA0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEA1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEA2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEA3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEA4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEA5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEA6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEA7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEA8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEA9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEA10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEA11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEA12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEA13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEA14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEA15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERB", description: "MCBSP Receive channel enable partition B", offset: "0xF", size: "16",
		bits: [
			{ name: "RCEB0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEB1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEB2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEB3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEB4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEB5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEB6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEB7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEB8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEB9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEB10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEB11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEB12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEB13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEB14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEB15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERA", description: "MCBSP Transmit channel enable partition A", offset: "0x10", size: "16",
		bits: [
			{ name: "XCERA0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERA1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERA2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERA3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERA4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERA5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERA6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERA7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERA8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERA9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERA10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERA11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERA12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERA13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERA14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERA15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERB", description: "MCBSP Transmit channel enable partition B", offset: "0x11", size: "16",
		bits: [
			{ name: "XCERB0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERB1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERB2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERB3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERB4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERB5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERB6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERB7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERB8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERB9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERB10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERB11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERB12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERB13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERB14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERB15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "PCR", description: "MCBSP Pin control register bits 15-0", offset: "0x12", size: "16",
		bits: [
			{ name: "CLKRP", description: "Receive Clock polarity", size: "1", shift: "0", mask: "0x1" },
			{ name: "CLKXP", description: "Transmit clock polarity", size: "1", shift: "1", mask: "0x2" },
			{ name: "FSRP", description: "Receive Frame synchronization polarity", size: "1", shift: "2", mask: "0x4" },
			{ name: "FSXP", description: "Transmit Frame synchronization polarity", size: "1", shift: "3", mask: "0x8" },
			{ name: "DR_STAT", description: "DR pin status - reserved for this McBSP", size: "1", shift: "4", mask: "0x10" },
			{ name: "DX_STAT", description: "DX pin status - reserved for this McBSP", size: "1", shift: "5", mask: "0x20" },
			{ name: "CLKS_STAT", description: "CLKS pin status - reserved for 28x -McBSP", size: "1", shift: "6", mask: "0x40" },
			{ name: "SCLKME", description: "Enhanced sample clock mode selection bit.", size: "1", shift: "7", mask: "0x80" },
			{ name: "CLKRM", description: "Receiver Clock Mode", size: "1", shift: "8", mask: "0x100" },
			{ name: "CLKXM", description: "Transmitter Clock Mode.", size: "1", shift: "9", mask: "0x200" },
			{ name: "FSRM", description: "Receive Frame Synchronization Mode", size: "1", shift: "10", mask: "0x400" },
			{ name: "FSXM", description: "Transmit Frame Synchronization Mode", size: "1", shift: "11", mask: "0x800" },
			{ name: "RIOEN", description: "General Purpose I/O Mode - reserved in", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XIOEN", description: "General Purpose I/O Mode - reserved in", size: "1", shift: "13", mask: "0x2000" },
			{ name: "IDEL_EN", description: "reserved in this 28x-McBSP", size: "1", shift: "14", mask: "0x4000" },
		]
	},
	{ name: "RCERC", description: "MCBSP Receive channel enable partition C", offset: "0x13", size: "16",
		bits: [
			{ name: "RCEC0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEC1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEC2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEC3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEC4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEC5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEC6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEC7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEC8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEC9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEC10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEC11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEC12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEC13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEC14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEC15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERD", description: "MCBSP Receive channel enable partition D", offset: "0x14", size: "16",
		bits: [
			{ name: "RCED0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCED1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCED2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCED3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCED4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCED5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCED6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCED7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCED8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCED9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCED10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCED11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCED12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCED13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCED14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCED15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERC", description: "MCBSP Transmit channel enable partition C", offset: "0x15", size: "16",
		bits: [
			{ name: "XCERC0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERC1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERC2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERC3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERC4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERC5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERC6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERC7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERC8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERC9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERC10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERC11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERC12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERC13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERC14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERC15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERD", description: "MCBSP Transmit channel enable partition D", offset: "0x16", size: "16",
		bits: [
			{ name: "XCERD0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERD1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERD2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERD3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERD4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERD5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERD6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERD7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERD8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERD9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERD10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERD11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERD12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERD13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERD14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERD15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERE", description: "MCBSP Receive channel enable partition E", offset: "0x17", size: "16",
		bits: [
			{ name: "RCEE0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEE1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEE2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEE3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEE4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEE5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEE6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEE7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEE8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEE9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEE10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEE11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEE12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEE13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEE14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEE15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERF", description: "MCBSP Receive channel enable partition F", offset: "0x18", size: "16",
		bits: [
			{ name: "RCEF0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEF1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEF2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEF3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEF4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEF5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEF6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEF7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEF8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEF9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEF10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEF11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEF12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEF13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEF14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEF15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERE", description: "MCBSP Transmit channel enable partition E", offset: "0x19", size: "16",
		bits: [
			{ name: "XCERE0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERE1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERE2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERE3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERE4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERE5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERE6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERE7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERE8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERE9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERE10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERE11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERE12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERE13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERE14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERE15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERF", description: "MCBSP Transmit channel enable partition F", offset: "0x1A", size: "16",
		bits: [
			{ name: "XCERF0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERF1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERF2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERF3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERF4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERF5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERF6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERF7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERF8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERF9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERF10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERF11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERF12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERF13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERF14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERF15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERG", description: "MCBSP Receive channel enable partition G", offset: "0x1B", size: "16",
		bits: [
			{ name: "RCEG0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEG1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEG2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEG3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEG4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEG5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEG6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEG7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEG8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEG9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEG10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEG11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEG12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEG13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEG14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEG15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "RCERH", description: "MCBSP Receive channel enable partition H", offset: "0x1C", size: "16",
		bits: [
			{ name: "RCEH0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "RCEH1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "RCEH2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "RCEH3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "RCEH4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "RCEH5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "RCEH6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "RCEH7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "RCEH8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "RCEH9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "RCEH10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "RCEH11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "RCEH12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RCEH13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "RCEH14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "RCEH15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERG", description: "MCBSP Transmit channel enable partition G", offset: "0x1D", size: "16",
		bits: [
			{ name: "XCERG0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCERG1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCERG2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCERG3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCERG4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCERG5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCERG6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCERG7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCERG8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCERG9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCERG10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCERG11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCERG12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCERG13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCERG14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCERG15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "XCERH", description: "MCBSP Transmit channel enable partition H", offset: "0x1E", size: "16",
		bits: [
			{ name: "XCEH0", description: "Receive Channel enable bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "XCEH1", description: "Receive Channel enable bit", size: "1", shift: "1", mask: "0x2" },
			{ name: "XCEH2", description: "Receive Channel enable bit", size: "1", shift: "2", mask: "0x4" },
			{ name: "XCEH3", description: "Receive Channel enable bit", size: "1", shift: "3", mask: "0x8" },
			{ name: "XCEH4", description: "Receive Channel enable bit", size: "1", shift: "4", mask: "0x10" },
			{ name: "XCEH5", description: "Receive Channel enable bit", size: "1", shift: "5", mask: "0x20" },
			{ name: "XCEH6", description: "Receive Channel enable bit", size: "1", shift: "6", mask: "0x40" },
			{ name: "XCEH7", description: "Receive Channel enable bit", size: "1", shift: "7", mask: "0x80" },
			{ name: "XCEH8", description: "Receive Channel enable bit", size: "1", shift: "8", mask: "0x100" },
			{ name: "XCEH9", description: "Receive Channel enable bit", size: "1", shift: "9", mask: "0x200" },
			{ name: "XCEH10", description: "Receive Channel enable bit", size: "1", shift: "10", mask: "0x400" },
			{ name: "XCEH11", description: "Receive Channel enable bit", size: "1", shift: "11", mask: "0x800" },
			{ name: "XCEH12", description: "Receive Channel enable bit", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XCEH13", description: "Receive Channel enable bit", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XCEH14", description: "Receive Channel enable bit", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XCEH15", description: "Receive Channel enable bit", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "MFFINT", description: "MCBSP Interrupt enable register for", offset: "0x23", size: "16",
		bits: [
			{ name: "XINT", description: "XINT  interrupt enable", size: "1", shift: "0", mask: "0x1" },
			{ name: "RINT", description: "RINT  interrupt enable", size: "1", shift: "2", mask: "0x4" },
		]
	},
];
module.exports = {
	mcbspRegisters: MCBSP_REGISTERS,
}
