let OUTPUTXBAR_REGISTERS = [
	{ name: "OUTPUT1MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 1", offset: "0x0", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT1MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 1", offset: "0x2", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT1 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT2MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 2", offset: "0x4", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT2MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 2", offset: "0x6", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT2 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT3MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 3", offset: "0x8", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT3MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 3", offset: "0xA", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT3 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT4MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 4", offset: "0xC", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT4MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 4", offset: "0xE", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT4 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT5MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 5", offset: "0x10", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT5MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 5", offset: "0x12", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT5 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT6MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 6", offset: "0x14", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT6MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 6", offset: "0x16", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT6 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT7MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 7", offset: "0x18", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT7MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 7", offset: "0x1A", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT7 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT8MUX0TO15CFG", description: "Output X-BAR Mux Configuration for Output 8", offset: "0x1C", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "Mux1 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "Mux2 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "Mux3 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "Mux4 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "Mux5 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "Mux6 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "Mux7 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "Mux8 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "Mux9 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "Mux10 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "Mux11 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "Mux12 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "Mux13 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "Mux14 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "Mux15 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT8MUX16TO31CFG", description: "Output X-BAR Mux Configuration for Output 8", offset: "0x1E", size: "32",
		bits: [
			{ name: "MUX16", description: "Mux16 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "Mux17 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX18", description: "Mux18 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX19", description: "Mux19 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX20", description: "Mux20 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX21", description: "Mux21 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX22", description: "Mux22 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX23", description: "Mux23 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX24", description: "Mux24 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX25", description: "Mux25 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX26", description: "Mux26 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX27", description: "Mux27 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX28", description: "Mux28 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX29", description: "Mux29 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX30", description: "Mux30 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX31", description: "Mux31 Configuration for OUTPUT8 of OUTPUT-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "OUTPUT1MUXENABLE", description: "Output X-BAR Mux Enable  for Output 1", offset: "0x20", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT2MUXENABLE", description: "Output X-BAR Mux Enable  for Output 2", offset: "0x22", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT3MUXENABLE", description: "Output X-BAR Mux Enable  for Output 3", offset: "0x24", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT4MUXENABLE", description: "Output X-BAR Mux Enable  for Output 4", offset: "0x26", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT5MUXENABLE", description: "Output X-BAR Mux Enable  for Output 5", offset: "0x28", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT6MUXENABLE", description: "Output X-BAR Mux Enable  for Output 6", offset: "0x2A", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT7MUXENABLE", description: "Output X-BAR Mux Enable  for Output 7", offset: "0x2C", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUT8MUXENABLE", description: "Output X-BAR Mux Enable  for Output 8", offset: "0x2E", size: "32",
		bits: [
			{ name: "MUX0", description: "Mux0 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "Mux1 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "Mux2 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "Mux3 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "Mux4 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "Mux5 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "Mux6 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "Mux7 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "Mux8 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "Mux9 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "Mux10 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "Mux11 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "Mux12 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "Mux13 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "Mux14 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "Mux15 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "Mux16 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "Mux17 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "17", mask: "0x20000" },
			{ name: "MUX18", description: "Mux18 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "18", mask: "0x40000" },
			{ name: "MUX19", description: "Mux19 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "19", mask: "0x80000" },
			{ name: "MUX20", description: "Mux20 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "20", mask: "0x100000" },
			{ name: "MUX21", description: "Mux21 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "21", mask: "0x200000" },
			{ name: "MUX22", description: "Mux22 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "22", mask: "0x400000" },
			{ name: "MUX23", description: "Mux23 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "23", mask: "0x800000" },
			{ name: "MUX24", description: "Mux24 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "MUX25", description: "Mux25 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "MUX26", description: "Mux26 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "MUX27", description: "Mux27 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "MUX28", description: "Mux28 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "MUX29", description: "Mux29 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "MUX30", description: "Mux30 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "MUX31", description: "Mux31 to drive OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "OUTPUTLATCH", description: "Output X-BAR Output Latch", offset: "0x30", size: "32",
		bits: [
			{ name: "OUTPUT1", description: "Records the OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUTPUT2", description: "Records the OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUTPUT3", description: "Records the OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUTPUT4", description: "Records the OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUTPUT5", description: "Records the OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUTPUT6", description: "Records the OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUTPUT7", description: "Records the OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUTPUT8", description: "Records the OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "OUTPUTLATCHCLR", description: "Output X-BAR Output Latch Clear", offset: "0x32", size: "32",
		bits: [
			{ name: "OUTPUT1", description: "Clears the Output-Latch for OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUTPUT2", description: "Clears the Output-Latch for OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUTPUT3", description: "Clears the Output-Latch for OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUTPUT4", description: "Clears the Output-Latch for OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUTPUT5", description: "Clears the Output-Latch for OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUTPUT6", description: "Clears the Output-Latch for OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUTPUT7", description: "Clears the Output-Latch for OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUTPUT8", description: "Clears the Output-Latch for OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "OUTPUTLATCHFRC", description: "Output X-BAR Output Latch Clear", offset: "0x34", size: "32",
		bits: [
			{ name: "OUTPUT1", description: "Sets the Output-Latch for OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUTPUT2", description: "Sets the Output-Latch for OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUTPUT3", description: "Sets the Output-Latch for OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUTPUT4", description: "Sets the Output-Latch for OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUTPUT5", description: "Sets the Output-Latch for OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUTPUT6", description: "Sets the Output-Latch for OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUTPUT7", description: "Sets the Output-Latch for OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUTPUT8", description: "Sets the Output-Latch for OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "OUTPUTLATCHENABLE", description: "Output X-BAR Output Latch Enable", offset: "0x36", size: "32",
		bits: [
			{ name: "OUTPUT1", description: "Selects the output latch to drive OUTPUT1 for OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUTPUT2", description: "Selects the output latch to drive OUTPUT2 for OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUTPUT3", description: "Selects the output latch to drive OUTPUT3 for OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUTPUT4", description: "Selects the output latch to drive OUTPUT4 for OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUTPUT5", description: "Selects the output latch to drive OUTPUT5 for OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUTPUT6", description: "Selects the output latch to drive OUTPUT6 for OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUTPUT7", description: "Selects the output latch to drive OUTPUT7 for OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUTPUT8", description: "Selects the output latch to drive OUTPUT8 for OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "OUTPUTINV", description: "Output X-BAR Output Inversion", offset: "0x38", size: "32",
		bits: [
			{ name: "OUTPUT1", description: "Selects polarity for OUTPUT1 of OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUTPUT2", description: "Selects polarity for OUTPUT2 of OUTPUT-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUTPUT3", description: "Selects polarity for OUTPUT3 of OUTPUT-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUTPUT4", description: "Selects polarity for OUTPUT4 of OUTPUT-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUTPUT5", description: "Selects polarity for OUTPUT5 of OUTPUT-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUTPUT6", description: "Selects polarity for OUTPUT6 of OUTPUT-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUTPUT7", description: "Selects polarity for OUTPUT7 of OUTPUT-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUTPUT8", description: "Selects polarity for OUTPUT8 of OUTPUT-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "OUTPUTLOCK", description: "Output X-BAR Configuration Lock register", offset: "0x3E", size: "32",
		bits: [
			{ name: "LOCK", description: "Locks the configuration for OUTPUT-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "KEY", description: "Write Protection KEY", size: "16", shift: "16", mask: "0xFFFF0000" },
		]
	},
];
module.exports = {
	outputxbarRegisters: OUTPUTXBAR_REGISTERS,
}
