let PWM_XBAR_REGISTERS = [
	{ name: "TRIP1MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output1", offset: "0x0", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP1MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output1", offset: "0x2", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT1 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP2MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output2", offset: "0x4", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP2MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output2", offset: "0x6", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT2 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP3MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output3", offset: "0x8", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP3MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output3", offset: "0xA", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT3 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP4MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output4", offset: "0xC", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP4MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output4", offset: "0xE", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT4 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP5MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output5", offset: "0x10", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP5MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output5", offset: "0x12", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT5 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP6MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output6", offset: "0x14", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP6MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output6", offset: "0x16", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT6 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP7MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output7", offset: "0x18", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP7MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output7", offset: "0x1A", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT7 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP8MUX0TO15CFG", description: "PWM XBAR Mux Configuration for Output8", offset: "0x1C", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX1", description: "MUX1 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
			{ name: "MUX2", description: "MUX2 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "4", mask: "0x30" },
			{ name: "MUX3", description: "MUX3 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "6", mask: "0xC0" },
			{ name: "MUX4", description: "MUX4 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "8", mask: "0x300" },
			{ name: "MUX5", description: "MUX5 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "10", mask: "0xC00" },
			{ name: "MUX6", description: "MUX6 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "12", mask: "0x3000" },
			{ name: "MUX7", description: "MUX7 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "14", mask: "0xC000" },
			{ name: "MUX8", description: "MUX8 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "16", mask: "0x30000" },
			{ name: "MUX9", description: "MUX9 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "18", mask: "0xC0000" },
			{ name: "MUX10", description: "MUX10 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "20", mask: "0x300000" },
			{ name: "MUX11", description: "MUX11 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "22", mask: "0xC00000" },
			{ name: "MUX12", description: "MUX12 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "24", mask: "0x3000000" },
			{ name: "MUX13", description: "MUX13 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "26", mask: "0xC000000" },
			{ name: "MUX14", description: "MUX14 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "28", mask: "0x30000000" },
			{ name: "MUX15", description: "MUX15 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "TRIP8MUX16TO31CFG", description: "PWM XBAR Mux Configuration for Output8", offset: "0x1E", size: "32",
		bits: [
			{ name: "MUX16", description: "MUX16 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "0", mask: "0x3" },
			{ name: "MUX17", description: "MUX17 Configuration for OUT8 of EPWM-XBAR", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "TRIP1MUXENABLE", description: "PWM XBAR Mux Enable for Output1", offset: "0x20", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT1 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT1 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT1 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT1 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT1 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT1 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT1 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT1 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT1 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT1 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT1 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT1 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT1 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT1 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT1 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT1 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT1 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT1 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP2MUXENABLE", description: "PWM XBAR Mux Enable for Output2", offset: "0x22", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT2 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT2 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT2 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT2 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT2 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT2 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT2 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT2 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT2 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT2 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT2 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT2 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT2 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT2 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT2 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT2 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT2 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT2 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP3MUXENABLE", description: "PWM XBAR Mux Enable for Output3", offset: "0x24", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT3 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT3 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT3 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT3 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT3 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT3 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT3 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT3 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT3 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT3 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT3 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT3 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT3 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT3 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT3 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT3 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT3 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT3 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP4MUXENABLE", description: "PWM XBAR Mux Enable for Output4", offset: "0x26", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT4 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT4 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT4 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT4 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT4 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT4 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT4 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT4 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT4 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT4 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT4 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT4 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT4 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT4 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT4 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT4 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT4 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT4 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP5MUXENABLE", description: "PWM XBAR Mux Enable for Output5", offset: "0x28", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT5 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT5 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT5 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT5 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT5 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT5 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT5 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT5 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT5 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT5 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT5 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT5 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT5 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT5 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT5 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT5 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT5 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT5 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP6MUXENABLE", description: "PWM XBAR Mux Enable for Output6", offset: "0x2A", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT6 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT6 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT6 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT6 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT6 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT6 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT6 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT6 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT6 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT6 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT6 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT6 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT6 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT6 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT6 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT6 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT6 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT6 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP7MUXENABLE", description: "PWM XBAR Mux Enable for Output7", offset: "0x2C", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT7 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT7 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT7 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT7 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT7 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT7 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT7 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT7 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT7 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT7 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT7 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT7 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT7 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT7 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT7 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT7 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT7 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT7 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIP8MUXENABLE", description: "PWM XBAR Mux Enable for Output8", offset: "0x2E", size: "32",
		bits: [
			{ name: "MUX0", description: "MUX0 to drive OUT8 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "MUX1", description: "MUX1 to drive OUT8 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "MUX2", description: "MUX2 to drive OUT8 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "MUX3", description: "MUX3 to drive OUT8 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "MUX4", description: "MUX4 to drive OUT8 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "MUX5", description: "MUX5 to drive OUT8 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "MUX6", description: "MUX6 to drive OUT8 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "MUX7", description: "MUX7 to drive OUT8 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
			{ name: "MUX8", description: "MUX8 to drive OUT8 of EPWM-XBAR", size: "1", shift: "8", mask: "0x100" },
			{ name: "MUX9", description: "MUX9 to drive OUT8 of EPWM-XBAR", size: "1", shift: "9", mask: "0x200" },
			{ name: "MUX10", description: "MUX10 to drive OUT8 of EPWM-XBAR", size: "1", shift: "10", mask: "0x400" },
			{ name: "MUX11", description: "MUX11 to drive OUT8 of EPWM-XBAR", size: "1", shift: "11", mask: "0x800" },
			{ name: "MUX12", description: "MUX12 to drive OUT8 of EPWM-XBAR", size: "1", shift: "12", mask: "0x1000" },
			{ name: "MUX13", description: "MUX13 to drive OUT8 of EPWM-XBAR", size: "1", shift: "13", mask: "0x2000" },
			{ name: "MUX14", description: "MUX14 to drive OUT8 of EPWM-XBAR", size: "1", shift: "14", mask: "0x4000" },
			{ name: "MUX15", description: "MUX15 to drive OUT8 of EPWM-XBAR", size: "1", shift: "15", mask: "0x8000" },
			{ name: "MUX16", description: "MUX16 to drive OUT8 of EPWM-XBAR", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MUX17", description: "MUX17 to drive OUT8 of EPWM-XBAR", size: "1", shift: "17", mask: "0x20000" },
		]
	},
	{ name: "TRIPOUTINV", description: "PWM XBAR Output Inversion Register", offset: "0x38", size: "32",
		bits: [
			{ name: "OUT1", description: "Selects polarity for OUT1 of EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "OUT2", description: "Selects polarity for OUT2 of EPWM-XBAR", size: "1", shift: "1", mask: "0x2" },
			{ name: "OUT3", description: "Selects polarity for OUT3 of EPWM-XBAR", size: "1", shift: "2", mask: "0x4" },
			{ name: "OUT4", description: "Selects polarity for OUT4 of EPWM-XBAR", size: "1", shift: "3", mask: "0x8" },
			{ name: "OUT5", description: "Selects polarity for OUT5 of EPWM-XBAR", size: "1", shift: "4", mask: "0x10" },
			{ name: "OUT6", description: "Selects polarity for OUT6 of EPWM-XBAR", size: "1", shift: "5", mask: "0x20" },
			{ name: "OUT7", description: "Selects polarity for OUT7 of EPWM-XBAR", size: "1", shift: "6", mask: "0x40" },
			{ name: "OUT8", description: "Selects polarity for OUT8 of EPWM-XBAR", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "TRIPLOCK", description: "PWM XBAR Configuration Lock register", offset: "0x3E", size: "32",
		bits: [
			{ name: "LOCK", description: "Locks the configuration for EPWM-XBAR", size: "1", shift: "0", mask: "0x1" },
			{ name: "KEY", description: "Write protection KEY", size: "16", shift: "16", mask: "0xFFFF0000" },
		]
	},
];
module.exports = {
	pwm_xbarRegisters: PWM_XBAR_REGISTERS,
}
