let interrupts = [
	{ intDefineName: "INT_TIMER1", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "CPU Timer 1 Interrupt" },
	{ intDefineName: "INT_TIMER2", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "CPU Timer 2 Interrupt" },
	{ intDefineName: "INT_DATALOG", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Datalogging Interrupt" },
	{ intDefineName: "INT_RTOS", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "RTOS Interrupt from ERAD" },
	{ intDefineName: "INT_EMU", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Emulation Interrupt" },
	{ intDefineName: "INT_NMI", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Non-Maskable Interrupt" },
	{ intDefineName: "INT_ILLEGAL", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Illegal Operation Trap" },
	{ intDefineName: "INT_USER1", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 1" },
	{ intDefineName: "INT_USER2", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 2" },
	{ intDefineName: "INT_USER3", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 3" },
	{ intDefineName: "INT_USER4", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 4" },
	{ intDefineName: "INT_USER5", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 5" },
	{ intDefineName: "INT_USER6", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 6" },
	{ intDefineName: "INT_USER7", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 7" },
	{ intDefineName: "INT_USER8", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 8" },
	{ intDefineName: "INT_USER9", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 9" },
	{ intDefineName: "INT_USER10", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 10" },
	{ intDefineName: "INT_USER11", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 11" },
	{ intDefineName: "INT_USER12", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 12" },
	{ intDefineName: "INT_ADCA1", intGroupChannelNumber: "1.1", intGroupNumber: "1", intChannelNumber: "1", intDescription: "ADCA Interrupt 1" },
	{ intDefineName: "INT_ADCC1", intGroupChannelNumber: "1.2", intGroupNumber: "1", intChannelNumber: "2", intDescription: "ADCC Interrupt 1" },
	{ intDefineName: "INT_XINT1", intGroupChannelNumber: "1.4", intGroupNumber: "1", intChannelNumber: "4", intDescription: "XINT1 Interrupt" },
	{ intDefineName: "INT_XINT2", intGroupChannelNumber: "1.5", intGroupNumber: "1", intChannelNumber: "5", intDescription: "XINT2 Interrupt" },
	{ intDefineName: "INT_SYS_ERR", intGroupChannelNumber: "1.6", intGroupNumber: "1", intChannelNumber: "6", intDescription: "SYS_ERR Interrupt" },
	{ intDefineName: "INT_TIMER0", intGroupChannelNumber: "1.7", intGroupNumber: "1", intChannelNumber: "7", intDescription: "Timer 0 Interrupt" },
	{ intDefineName: "INT_WAKE", intGroupChannelNumber: "1.8", intGroupNumber: "1", intChannelNumber: "8", intDescription: "Standby and Halt Wakeup Interrupt" },
	{ intDefineName: "INT_EPWM1_TZ", intGroupChannelNumber: "2.1", intGroupNumber: "2", intChannelNumber: "1", intDescription: "ePWM1 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM2_TZ", intGroupChannelNumber: "2.2", intGroupNumber: "2", intChannelNumber: "2", intDescription: "ePWM2 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM3_TZ", intGroupChannelNumber: "2.3", intGroupNumber: "2", intChannelNumber: "3", intDescription: "ePWM3 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM4_TZ", intGroupChannelNumber: "2.4", intGroupNumber: "2", intChannelNumber: "4", intDescription: "ePWM4 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM5_TZ", intGroupChannelNumber: "2.5", intGroupNumber: "2", intChannelNumber: "5", intDescription: "ePWM5 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM6_TZ", intGroupChannelNumber: "2.6", intGroupNumber: "2", intChannelNumber: "6", intDescription: "ePWM6 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM7_TZ", intGroupChannelNumber: "2.7", intGroupNumber: "2", intChannelNumber: "7", intDescription: "ePWM7 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM1", intGroupChannelNumber: "3.1", intGroupNumber: "3", intChannelNumber: "1", intDescription: "ePWM1 Interrupt" },
	{ intDefineName: "INT_EPWM2", intGroupChannelNumber: "3.2", intGroupNumber: "3", intChannelNumber: "2", intDescription: "ePWM2 Interrupt" },
	{ intDefineName: "INT_EPWM3", intGroupChannelNumber: "3.3", intGroupNumber: "3", intChannelNumber: "3", intDescription: "ePWM3 Interrupt" },
	{ intDefineName: "INT_EPWM4", intGroupChannelNumber: "3.4", intGroupNumber: "3", intChannelNumber: "4", intDescription: "ePWM4 Interrupt" },
	{ intDefineName: "INT_EPWM5", intGroupChannelNumber: "3.5", intGroupNumber: "3", intChannelNumber: "5", intDescription: "ePWM5 Interrupt" },
	{ intDefineName: "INT_EPWM6", intGroupChannelNumber: "3.6", intGroupNumber: "3", intChannelNumber: "6", intDescription: "ePWM6 Interrupt" },
	{ intDefineName: "INT_EPWM7", intGroupChannelNumber: "3.7", intGroupNumber: "3", intChannelNumber: "7", intDescription: "ePWM7 Interrupt" },
	{ intDefineName: "INT_ECAP1", intGroupChannelNumber: "4.1", intGroupNumber: "4", intChannelNumber: "1", intDescription: "eCAP1 Interrupt" },
	{ intDefineName: "INT_ECAP2", intGroupChannelNumber: "4.2", intGroupNumber: "4", intChannelNumber: "2", intDescription: "eCAP2 Interrupt" },
	{ intDefineName: "INT_EQEP1", intGroupChannelNumber: "5.1", intGroupNumber: "5", intChannelNumber: "1", intDescription: "eQEP1 Interrupt" },
	{ intDefineName: "INT_SPIA_RX", intGroupChannelNumber: "6.1", intGroupNumber: "6", intChannelNumber: "1", intDescription: "SPIA Receive Interrupt" },
	{ intDefineName: "INT_SPIA_TX", intGroupChannelNumber: "6.2", intGroupNumber: "6", intChannelNumber: "2", intDescription: "SPIA Transmit Interrupt" },
	{ intDefineName: "INT_DCC0", intGroupChannelNumber: "6.7", intGroupNumber: "6", intChannelNumber: "7", intDescription: "DCC0 Interrupt" },
	{ intDefineName: "INT_I2CA", intGroupChannelNumber: "8.1", intGroupNumber: "8", intChannelNumber: "1", intDescription: "I2CA Interrupt 1" },
	{ intDefineName: "INT_I2CA_FIFO", intGroupChannelNumber: "8.2", intGroupNumber: "8", intChannelNumber: "2", intDescription: "I2CA Interrupt 2" },
	{ intDefineName: "INT_I2CB", intGroupChannelNumber: "8.3", intGroupNumber: "8", intChannelNumber: "3", intDescription: "I2CB Interrupt 1" },
	{ intDefineName: "INT_I2CB_FIFO", intGroupChannelNumber: "8.4", intGroupNumber: "8", intChannelNumber: "4", intDescription: "I2CB Interrupt 2" },
	{ intDefineName: "INT_SCIC_RX", intGroupChannelNumber: "8.5", intGroupNumber: "8", intChannelNumber: "5", intDescription: "SCIC Receive Interrupt" },
	{ intDefineName: "INT_SCIC_TX", intGroupChannelNumber: "8.6", intGroupNumber: "8", intChannelNumber: "6", intDescription: "SCIC Transmit Interrupt" },
	{ intDefineName: "INT_SCIA_RX", intGroupChannelNumber: "9.1", intGroupNumber: "9", intChannelNumber: "1", intDescription: "SCIA Receive Interrupt" },
	{ intDefineName: "INT_SCIA_TX", intGroupChannelNumber: "9.2", intGroupNumber: "9", intChannelNumber: "2", intDescription: "SCIA Transmit Interrupt" },
	{ intDefineName: "INT_SCIB_RX", intGroupChannelNumber: "9.3", intGroupNumber: "9", intChannelNumber: "3", intDescription: "SCIB Receive Interrupt" },
	{ intDefineName: "INT_SCIB_TX", intGroupChannelNumber: "9.4", intGroupNumber: "9", intChannelNumber: "4", intDescription: "SCIB Transmit Interrupt" },
	{ intDefineName: "INT_CANA0", intGroupChannelNumber: "9.5", intGroupNumber: "9", intChannelNumber: "5", intDescription: "CANA Interrupt 0" },
	{ intDefineName: "INT_CANA1", intGroupChannelNumber: "9.6", intGroupNumber: "9", intChannelNumber: "6", intDescription: "CANA Interrupt 1" },
	{ intDefineName: "INT_ADCA_EVT", intGroupChannelNumber: "10.1", intGroupNumber: "10", intChannelNumber: "1", intDescription: "ADCA Event Interrupt" },
	{ intDefineName: "INT_ADCA2", intGroupChannelNumber: "10.2", intGroupNumber: "10", intChannelNumber: "2", intDescription: "ADCA Interrupt 2" },
	{ intDefineName: "INT_ADCA3", intGroupChannelNumber: "10.3", intGroupNumber: "10", intChannelNumber: "3", intDescription: "ADCA Interrupt 3" },
	{ intDefineName: "INT_ADCA4", intGroupChannelNumber: "10.4", intGroupNumber: "10", intChannelNumber: "4", intDescription: "ADCA Interrupt 4" },
	{ intDefineName: "INT_ADCC_EVT", intGroupChannelNumber: "10.5", intGroupNumber: "10", intChannelNumber: "5", intDescription: "ADCC Event Interrupt" },
	{ intDefineName: "INT_ADCC2", intGroupChannelNumber: "10.6", intGroupNumber: "10", intChannelNumber: "6", intDescription: "ADCC Interrupt 2" },
	{ intDefineName: "INT_ADCC3", intGroupChannelNumber: "10.7", intGroupNumber: "10", intChannelNumber: "7", intDescription: "ADCC Interrupt 3" },
	{ intDefineName: "INT_ADCC4", intGroupChannelNumber: "10.8", intGroupNumber: "10", intChannelNumber: "8", intDescription: "ADCC Interrupt 4" },
	{ intDefineName: "INT_XINT3", intGroupChannelNumber: "12.1", intGroupNumber: "12", intChannelNumber: "1", intDescription: "XINT3 Interrupt" },
	{ intDefineName: "INT_XINT4", intGroupChannelNumber: "12.2", intGroupNumber: "12", intChannelNumber: "2", intDescription: "XINT4 Interrupt" },
	{ intDefineName: "INT_XINT5", intGroupChannelNumber: "12.3", intGroupNumber: "12", intChannelNumber: "3", intDescription: "XINT5 Interrupt" },
	{ intDefineName: "INT_FLSS", intGroupChannelNumber: "12.5", intGroupNumber: "12", intChannelNumber: "5", intDescription: "Interrupt from flash sub-system" },
];
module.exports = {
	interrupts: interrupts,
}
