let interrupts = [
	{ intDefineName: "INT_TIMER1", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "CPU Timer 1 Interrupt" },
	{ intDefineName: "INT_TIMER2", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "CPU Timer 2 Interrupt" },
	{ intDefineName: "INT_DATALOG", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Datalogging Interrupt" },
	{ intDefineName: "INT_RTOS", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "RTOS Interrupt from ERAD" },
	{ intDefineName: "INT_EMU", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Emulation Interrupt" },
	{ intDefineName: "INT_NMI", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Non-Maskable Interrupt" },
	{ intDefineName: "INT_ILLEGAL", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "Illegal Operation Trap" },
	{ intDefineName: "INT_USER1", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 1" },
	{ intDefineName: "INT_USER2", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 2" },
	{ intDefineName: "INT_USER3", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 3" },
	{ intDefineName: "INT_USER4", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 4" },
	{ intDefineName: "INT_USER5", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 5" },
	{ intDefineName: "INT_USER6", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 6" },
	{ intDefineName: "INT_USER7", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 7" },
	{ intDefineName: "INT_USER8", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 8" },
	{ intDefineName: "INT_USER9", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 9" },
	{ intDefineName: "INT_USER10", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 10" },
	{ intDefineName: "INT_USER11", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 11" },
	{ intDefineName: "INT_USER12", intGroupChannelNumber: "OTHER", intGroupNumber: "", intChannelNumber: "", intDescription: "User Defined Trap 12" },
	{ intDefineName: "INT_ADCA1", intGroupChannelNumber: "1.1", intGroupNumber: "1", intChannelNumber: "1", intDescription: "ADCA Interrupt 1" },
	{ intDefineName: "INT_ADCB1", intGroupChannelNumber: "1.2", intGroupNumber: "1", intChannelNumber: "2", intDescription: "ADCB Interrupt 1" },
	{ intDefineName: "INT_ADCC1", intGroupChannelNumber: "1.3", intGroupNumber: "1", intChannelNumber: "3", intDescription: "ADCC Interrupt 1" },
	{ intDefineName: "INT_XINT1", intGroupChannelNumber: "1.4", intGroupNumber: "1", intChannelNumber: "4", intDescription: "XINT1 Interrupt" },
	{ intDefineName: "INT_XINT2", intGroupChannelNumber: "1.5", intGroupNumber: "1", intChannelNumber: "5", intDescription: "XINT2 Interrupt" },
	{ intDefineName: "INT_SYS_ERR", intGroupChannelNumber: "1.6", intGroupNumber: "1", intChannelNumber: "6", intDescription: "SYS_ERR Interrupt" },
	{ intDefineName: "INT_TIMER0", intGroupChannelNumber: "1.7", intGroupNumber: "1", intChannelNumber: "7", intDescription: "Timer 0 Interrupt" },
	{ intDefineName: "INT_WAKE", intGroupChannelNumber: "1.8", intGroupNumber: "1", intChannelNumber: "8", intDescription: "Standby and Halt Wakeup Interrupt" },
	{ intDefineName: "INT_EPWM1_TZ", intGroupChannelNumber: "2.1", intGroupNumber: "2", intChannelNumber: "1", intDescription: "ePWM1 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM2_TZ", intGroupChannelNumber: "2.2", intGroupNumber: "2", intChannelNumber: "2", intDescription: "ePWM2 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM3_TZ", intGroupChannelNumber: "2.3", intGroupNumber: "2", intChannelNumber: "3", intDescription: "ePWM3 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM4_TZ", intGroupChannelNumber: "2.4", intGroupNumber: "2", intChannelNumber: "4", intDescription: "ePWM4 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM5_TZ", intGroupChannelNumber: "2.5", intGroupNumber: "2", intChannelNumber: "5", intDescription: "ePWM5 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM6_TZ", intGroupChannelNumber: "2.6", intGroupNumber: "2", intChannelNumber: "6", intDescription: "ePWM6 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM7_TZ", intGroupChannelNumber: "2.7", intGroupNumber: "2", intChannelNumber: "7", intDescription: "ePWM7 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM8_TZ", intGroupChannelNumber: "2.8", intGroupNumber: "2", intChannelNumber: "8", intDescription: "ePWM8 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM1", intGroupChannelNumber: "3.1", intGroupNumber: "3", intChannelNumber: "1", intDescription: "ePWM1 Interrupt" },
	{ intDefineName: "INT_EPWM2", intGroupChannelNumber: "3.2", intGroupNumber: "3", intChannelNumber: "2", intDescription: "ePWM2 Interrupt" },
	{ intDefineName: "INT_EPWM3", intGroupChannelNumber: "3.3", intGroupNumber: "3", intChannelNumber: "3", intDescription: "ePWM3 Interrupt" },
	{ intDefineName: "INT_EPWM4", intGroupChannelNumber: "3.4", intGroupNumber: "3", intChannelNumber: "4", intDescription: "ePWM4 Interrupt" },
	{ intDefineName: "INT_EPWM5", intGroupChannelNumber: "3.5", intGroupNumber: "3", intChannelNumber: "5", intDescription: "ePWM5 Interrupt" },
	{ intDefineName: "INT_EPWM6", intGroupChannelNumber: "3.6", intGroupNumber: "3", intChannelNumber: "6", intDescription: "ePWM6 Interrupt" },
	{ intDefineName: "INT_EPWM7", intGroupChannelNumber: "3.7", intGroupNumber: "3", intChannelNumber: "7", intDescription: "ePWM7 Interrupt" },
	{ intDefineName: "INT_EPWM8", intGroupChannelNumber: "3.8", intGroupNumber: "3", intChannelNumber: "8", intDescription: "ePWM8 Interrupt" },
	{ intDefineName: "INT_ECAP1", intGroupChannelNumber: "4.1", intGroupNumber: "4", intChannelNumber: "1", intDescription: "eCAP1 Interrupt" },
	{ intDefineName: "INT_ECAP2", intGroupChannelNumber: "4.2", intGroupNumber: "4", intChannelNumber: "2", intDescription: "eCAP2 Interrupt" },
	{ intDefineName: "INT_EQEP1", intGroupChannelNumber: "5.1", intGroupNumber: "5", intChannelNumber: "1", intDescription: "eQEP1 Interrupt" },
	{ intDefineName: "INT_EQEP2", intGroupChannelNumber: "5.2", intGroupNumber: "5", intChannelNumber: "2", intDescription: "eQEP2 Interrupt" },
	{ intDefineName: "INT_EQEP3", intGroupChannelNumber: "5.3", intGroupNumber: "5", intChannelNumber: "3", intDescription: "eQEP3 Interrupt" },
	{ intDefineName: "INT_CLB1", intGroupChannelNumber: "5.5", intGroupNumber: "5", intChannelNumber: "5", intDescription: "CLB1 (Reconfigurable Logic) Interrupt" },
	{ intDefineName: "INT_CLB2", intGroupChannelNumber: "5.6", intGroupNumber: "5", intChannelNumber: "6", intDescription: "CLB2 (Reconfigurable Logic) Interrupt" },
	{ intDefineName: "INT_SPIA_RX", intGroupChannelNumber: "6.1", intGroupNumber: "6", intChannelNumber: "1", intDescription: "SPIA Receive Interrupt" },
	{ intDefineName: "INT_SPIA_TX", intGroupChannelNumber: "6.2", intGroupNumber: "6", intChannelNumber: "2", intDescription: "SPIA Transmit Interrupt" },
	{ intDefineName: "INT_SPIB_RX", intGroupChannelNumber: "6.3", intGroupNumber: "6", intChannelNumber: "3", intDescription: "SPIB Receive Interrupt" },
	{ intDefineName: "INT_SPIB_TX", intGroupChannelNumber: "6.4", intGroupNumber: "6", intChannelNumber: "4", intDescription: "SPIB Transmit Interrupt" },
	{ intDefineName: "INT_DCC0", intGroupChannelNumber: "6.7", intGroupNumber: "6", intChannelNumber: "7", intDescription: "DCC0 Interrupt" },
	{ intDefineName: "INT_DCC1", intGroupChannelNumber: "6.8", intGroupNumber: "6", intChannelNumber: "8", intDescription: "DCC1 Interrupt" },
	{ intDefineName: "INT_DMA_CH1", intGroupChannelNumber: "7.1", intGroupNumber: "7", intChannelNumber: "1", intDescription: "DMA Channel 1 Interrupt" },
	{ intDefineName: "INT_DMA_CH2", intGroupChannelNumber: "7.2", intGroupNumber: "7", intChannelNumber: "2", intDescription: "DMA Channel 2 Interrupt" },
	{ intDefineName: "INT_DMA_CH3", intGroupChannelNumber: "7.3", intGroupNumber: "7", intChannelNumber: "3", intDescription: "DMA Channel 3 Interrupt" },
	{ intDefineName: "INT_DMA_CH4", intGroupChannelNumber: "7.4", intGroupNumber: "7", intChannelNumber: "4", intDescription: "DMA Channel 4 Interrupt" },
	{ intDefineName: "INT_DMA_CH5", intGroupChannelNumber: "7.5", intGroupNumber: "7", intChannelNumber: "5", intDescription: "DMA Channel 5 Interrupt" },
	{ intDefineName: "INT_DMA_CH6", intGroupChannelNumber: "7.6", intGroupNumber: "7", intChannelNumber: "6", intDescription: "DMA Channel 6 Interrupt" },
	{ intDefineName: "INT_PMBUSA", intGroupChannelNumber: "7.7", intGroupNumber: "7", intChannelNumber: "7", intDescription: "PMBUSA Interrupt" },
	{ intDefineName: "INT_I2CA", intGroupChannelNumber: "8.1", intGroupNumber: "8", intChannelNumber: "1", intDescription: "I2CA Interrupt 1" },
	{ intDefineName: "INT_I2CA_FIFO", intGroupChannelNumber: "8.2", intGroupNumber: "8", intChannelNumber: "2", intDescription: "I2CA Interrupt 2" },
	{ intDefineName: "INT_I2CB", intGroupChannelNumber: "8.3", intGroupNumber: "8", intChannelNumber: "3", intDescription: "I2CB Interrupt 1" },
	{ intDefineName: "INT_I2CB_FIFO", intGroupChannelNumber: "8.4", intGroupNumber: "8", intChannelNumber: "4", intDescription: "I2CB Interrupt 2" },
	{ intDefineName: "INT_SCIC_RX", intGroupChannelNumber: "8.5", intGroupNumber: "8", intChannelNumber: "5", intDescription: "SCIC Receive Interrupt" },
	{ intDefineName: "INT_SCIC_TX", intGroupChannelNumber: "8.6", intGroupNumber: "8", intChannelNumber: "6", intDescription: "SCIC Transmit Interrupt" },
	{ intDefineName: "INT_SCIA_RX", intGroupChannelNumber: "9.1", intGroupNumber: "9", intChannelNumber: "1", intDescription: "SCIA Receive Interrupt" },
	{ intDefineName: "INT_SCIA_TX", intGroupChannelNumber: "9.2", intGroupNumber: "9", intChannelNumber: "2", intDescription: "SCIA Transmit Interrupt" },
	{ intDefineName: "INT_SCIB_RX", intGroupChannelNumber: "9.3", intGroupNumber: "9", intChannelNumber: "3", intDescription: "SCIB Receive Interrupt" },
	{ intDefineName: "INT_SCIB_TX", intGroupChannelNumber: "9.4", intGroupNumber: "9", intChannelNumber: "4", intDescription: "SCIB Transmit Interrupt" },
	{ intDefineName: "INT_MCANA_0", intGroupChannelNumber: "9.7", intGroupNumber: "9", intChannelNumber: "7", intDescription: "MCANSSA0" },
	{ intDefineName: "INT_MCANA_1", intGroupChannelNumber: "9.8", intGroupNumber: "9", intChannelNumber: "8", intDescription: "MCANSSA1" },
	{ intDefineName: "INT_ADCA_EVT", intGroupChannelNumber: "10.1", intGroupNumber: "10", intChannelNumber: "1", intDescription: "ADCA Event Interrupt" },
	{ intDefineName: "INT_ADCA2", intGroupChannelNumber: "10.2", intGroupNumber: "10", intChannelNumber: "2", intDescription: "ADCA Interrupt 2" },
	{ intDefineName: "INT_ADCA3", intGroupChannelNumber: "10.3", intGroupNumber: "10", intChannelNumber: "3", intDescription: "ADCA Interrupt 3" },
	{ intDefineName: "INT_ADCA4", intGroupChannelNumber: "10.4", intGroupNumber: "10", intChannelNumber: "4", intDescription: "ADCA Interrupt 4" },
	{ intDefineName: "INT_ADCB_EVT", intGroupChannelNumber: "10.5", intGroupNumber: "10", intChannelNumber: "5", intDescription: "ADCB Event Interrupt" },
	{ intDefineName: "INT_ADCB2", intGroupChannelNumber: "10.6", intGroupNumber: "10", intChannelNumber: "6", intDescription: "ADCB Interrupt 2" },
	{ intDefineName: "INT_ADCB3", intGroupChannelNumber: "10.7", intGroupNumber: "10", intChannelNumber: "7", intDescription: "ADCB Interrupt 3" },
	{ intDefineName: "INT_ADCB4", intGroupChannelNumber: "10.8", intGroupNumber: "10", intChannelNumber: "8", intDescription: "ADCB Interrupt 4" },
	{ intDefineName: "INT_CLA1_1", intGroupChannelNumber: "11.1", intGroupNumber: "11", intChannelNumber: "1", intDescription: "CLA1 Interrupt 1" },
	{ intDefineName: "INT_CLA1_2", intGroupChannelNumber: "11.2", intGroupNumber: "11", intChannelNumber: "2", intDescription: "CLA1 Interrupt 2" },
	{ intDefineName: "INT_CLA1_3", intGroupChannelNumber: "11.3", intGroupNumber: "11", intChannelNumber: "3", intDescription: "CLA1 Interrupt 3" },
	{ intDefineName: "INT_CLA1_4", intGroupChannelNumber: "11.4", intGroupNumber: "11", intChannelNumber: "4", intDescription: "CLA1 Interrupt 4" },
	{ intDefineName: "INT_CLA1_5", intGroupChannelNumber: "11.5", intGroupNumber: "11", intChannelNumber: "5", intDescription: "CLA1 Interrupt 5" },
	{ intDefineName: "INT_CLA1_6", intGroupChannelNumber: "11.6", intGroupNumber: "11", intChannelNumber: "6", intDescription: "CLA1 Interrupt 6" },
	{ intDefineName: "INT_CLA1_7", intGroupChannelNumber: "11.7", intGroupNumber: "11", intChannelNumber: "7", intDescription: "CLA1 Interrupt 7" },
	{ intDefineName: "INT_CLA1_8", intGroupChannelNumber: "11.8", intGroupNumber: "11", intChannelNumber: "8", intDescription: "CLA1 Interrupt 8" },
	{ intDefineName: "INT_XINT3", intGroupChannelNumber: "12.1", intGroupNumber: "12", intChannelNumber: "1", intDescription: "XINT3 Interrupt" },
	{ intDefineName: "INT_XINT4", intGroupChannelNumber: "12.2", intGroupNumber: "12", intChannelNumber: "2", intDescription: "XINT4 Interrupt" },
	{ intDefineName: "INT_XINT5", intGroupChannelNumber: "12.3", intGroupNumber: "12", intChannelNumber: "3", intDescription: "XINT5 Interrupt" },
	{ intDefineName: "INT_FLSS", intGroupChannelNumber: "12.5", intGroupNumber: "12", intChannelNumber: "5", intDescription: "Interrupt from flash sub-system" },
	{ intDefineName: "INT_VCU", intGroupChannelNumber: "12.6", intGroupNumber: "12", intChannelNumber: "6", intDescription: "VCU Interrupt (VCRC)" },
	{ intDefineName: "INT_MCANA_WAKE", intGroupChannelNumber: "12.7", intGroupNumber: "12", intChannelNumber: "7", intDescription: "MCANSSA_WAKE_AND_TS_PLS" },
	{ intDefineName: "INT_MCANA_ECC", intGroupChannelNumber: "12.8", intGroupNumber: "12", intChannelNumber: "8", intDescription: "MCANSSA_ECC_CORR_PLS" },
	{ intDefineName: "INT_ADCD1", intGroupChannelNumber: "1.9", intGroupNumber: "1", intChannelNumber: "9", intDescription: "ADCD Interrupt 1" },
	{ intDefineName: "INT_ADCE1", intGroupChannelNumber: "1.10", intGroupNumber: "1", intChannelNumber: "10", intDescription: "ADCE Interrupt 1" },
	{ intDefineName: "INT_EPWM9_TZ", intGroupChannelNumber: "2.9", intGroupNumber: "2", intChannelNumber: "9", intDescription: "ePWM9 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM10_TZ", intGroupChannelNumber: "2.10", intGroupNumber: "2", intChannelNumber: "10", intDescription: "ePWM9 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM11_TZ", intGroupChannelNumber: "2.11", intGroupNumber: "2", intChannelNumber: "11", intDescription: "ePWM10 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM12_TZ", intGroupChannelNumber: "2.12", intGroupNumber: "2", intChannelNumber: "12", intDescription: "ePWM10 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM9", intGroupChannelNumber: "3.9", intGroupNumber: "3", intChannelNumber: "9", intDescription: "ePWM9 Interrupt" },
	{ intDefineName: "INT_EPWM10", intGroupChannelNumber: "3.10", intGroupNumber: "3", intChannelNumber: "10", intDescription: "ePWM9 Interrupt" },
	{ intDefineName: "INT_EPWM11", intGroupChannelNumber: "3.11", intGroupNumber: "3", intChannelNumber: "11", intDescription: "ePWM10 Interrupt" },
	{ intDefineName: "INT_EPWM12", intGroupChannelNumber: "3.12", intGroupNumber: "3", intChannelNumber: "12", intDescription: "ePWM10 Interrupt" },
	{ intDefineName: "INT_FSITXA1", intGroupChannelNumber: "7.11", intGroupNumber: "7", intChannelNumber: "11", intDescription: "FSITXA_INT1 Interrupt" },
	{ intDefineName: "INT_FSITXA2", intGroupChannelNumber: "7.12", intGroupNumber: "7", intChannelNumber: "12", intDescription: "FSITXA_INT2 Interrupt" },
	{ intDefineName: "INT_FSIRXA1", intGroupChannelNumber: "7.13", intGroupNumber: "7", intChannelNumber: "13", intDescription: "FSIRXA_INT1 Interrupt" },
	{ intDefineName: "INT_FSIRXA2", intGroupChannelNumber: "7.14", intGroupNumber: "7", intChannelNumber: "14", intDescription: "FSIRXA_INT2 Interrupt" },
	{ intDefineName: "INT_LINA_0", intGroupChannelNumber: "8.9", intGroupNumber: "8", intChannelNumber: "9", intDescription: "LINA Interrupt0" },
	{ intDefineName: "INT_LINA_1", intGroupChannelNumber: "8.10", intGroupNumber: "8", intChannelNumber: "10", intDescription: "LINA Interrupt1" },
	{ intDefineName: "INT_MCANB_0", intGroupChannelNumber: "9.9", intGroupNumber: "9", intChannelNumber: "9", intDescription: "MCANSSB0" },
	{ intDefineName: "INT_MCANB_1", intGroupChannelNumber: "9.10", intGroupNumber: "9", intChannelNumber: "10", intDescription: "MCANSSB1" },
	{ intDefineName: "INT_MCANB_WAKE", intGroupChannelNumber: "9.11", intGroupNumber: "9", intChannelNumber: "11", intDescription: "MCANSSB_WAKE_AND_TS_PLS" },
	{ intDefineName: "INT_MCANB_ECC", intGroupChannelNumber: "9.12", intGroupNumber: "9", intChannelNumber: "12", intDescription: "MCANSSB_ECC_CORR_PLS" },
	{ intDefineName: "INT_USBA", intGroupChannelNumber: "9.15", intGroupNumber: "9", intChannelNumber: "15", intDescription: "USBA Interrupt" },
	{ intDefineName: "INT_ADCC_EVT", intGroupChannelNumber: "10.9", intGroupNumber: "10", intChannelNumber: "9", intDescription: "ADCC Event Interrupt" },
	{ intDefineName: "INT_ADCC2", intGroupChannelNumber: "10.10", intGroupNumber: "10", intChannelNumber: "10", intDescription: "ADCC Interrupt 2" },
	{ intDefineName: "INT_ADCC3", intGroupChannelNumber: "10.11", intGroupNumber: "10", intChannelNumber: "11", intDescription: "ADCC Interrupt 3" },
	{ intDefineName: "INT_ADCC4", intGroupChannelNumber: "10.12", intGroupNumber: "10", intChannelNumber: "12", intDescription: "ADCC Interrupt 4" },
	{ intDefineName: "INT_ADCD_EVT", intGroupChannelNumber: "10.13", intGroupNumber: "10", intChannelNumber: "13", intDescription: "ADCD Event Interrupt" },
	{ intDefineName: "INT_ADCD2", intGroupChannelNumber: "10.14", intGroupNumber: "10", intChannelNumber: "14", intDescription: "ADCD Interrupt 2" },
	{ intDefineName: "INT_ADCD3", intGroupChannelNumber: "10.15", intGroupNumber: "10", intChannelNumber: "15", intDescription: "ADCD Interrupt 3" },
	{ intDefineName: "INT_ADCD4", intGroupChannelNumber: "10.16", intGroupNumber: "10", intChannelNumber: "16", intDescription: "ADCD Interrupt 4" },
	{ intDefineName: "INT_ADCE_EVT", intGroupChannelNumber: "11.9", intGroupNumber: "11", intChannelNumber: "9", intDescription: "ADCE Event Interrupt" },
	{ intDefineName: "INT_ADCE2", intGroupChannelNumber: "11.10", intGroupNumber: "11", intChannelNumber: "10", intDescription: "ADCE Interrupt 2" },
	{ intDefineName: "INT_ADCE3", intGroupChannelNumber: "11.11", intGroupNumber: "11", intChannelNumber: "11", intDescription: "ADCE Interrupt 3" },
	{ intDefineName: "INT_ADCE4", intGroupChannelNumber: "11.12", intGroupNumber: "11", intChannelNumber: "12", intDescription: "ADCE Interrupt 4" },
	{ intDefineName: "INT_AES_SINTREQUEST", intGroupChannelNumber: "12.13", intGroupNumber: "12", intChannelNumber: "13", intDescription: "AES Interrupt" },
];
module.exports = {
	interrupts: interrupts,
}
