let interrupts = [
	{ intDefineName: "INT_CPU_OVF", intChannelNumber: "0", intDescription: "C29 CPU Overflow Interrupt" },
	{ intDefineName: "INT_CPU_UVF", intChannelNumber: "1", intDescription: "C29 CPU Underflow Interrupt" },
	{ intDefineName: "INT_CPU_DOV", intChannelNumber: "2", intDescription: "C29 CPU ? Interrupt" },
	{ intDefineName: "INT_WD", intChannelNumber: "3", intDescription: "Watchdog interrupt" },
	{ intDefineName: "INT_ERAD", intChannelNumber: "4", intDescription: "ERAD Interrupt" },
	{ intDefineName: "INT_DLT", intChannelNumber: "5", intDescription: "DLT Interrupt" },
	{ intDefineName: "INT_TIMER0", intChannelNumber: "6", intDescription: "Timer 0 Interrupt" },
	{ intDefineName: "INT_TIMER1", intChannelNumber: "7", intDescription: "Timer 1 Interrupt" },
	{ intDefineName: "INT_TIMER2", intChannelNumber: "8", intDescription: "Timer 2 Interrupt" },
	{ intDefineName: "INT_DEBUGSS", intChannelNumber: "9", intDescription: "Debug Interrupt" },
	{ intDefineName: "INT_ESM_LOWPRI", intChannelNumber: "10", intDescription: "ESM CPUx Low Priority Interrupt" },
	{ intDefineName: "INT_ESM_PARITYERR", intChannelNumber: "11", intDescription: "ESM Parity Error Interrupt" },
	{ intDefineName: "INT_IPC_1_1", intChannelNumber: "12", intDescription: "" },
	{ intDefineName: "INT_IPC_1_2", intChannelNumber: "13", intDescription: "" },
	{ intDefineName: "INT_IPC_1_3", intChannelNumber: "14", intDescription: "" },
	{ intDefineName: "INT_IPC_1_4", intChannelNumber: "15", intDescription: "" },
	{ intDefineName: "INT_IPC_2_1", intChannelNumber: "16", intDescription: "" },
	{ intDefineName: "INT_IPC_2_2", intChannelNumber: "17", intDescription: "" },
	{ intDefineName: "INT_IPC_2_3", intChannelNumber: "18", intDescription: "" },
	{ intDefineName: "INT_IPC_2_4", intChannelNumber: "19", intDescription: "" },
	{ intDefineName: "INT_IPC_HSM_RACK", intChannelNumber: "20", intDescription: "" },
	{ intDefineName: "INT_IPC_HSM_WDONE", intChannelNumber: "21", intDescription: "" },
	{ intDefineName: "INT_DTHE_TRNG", intChannelNumber: "26", intDescription: "TRNG Interrupt" },
	{ intDefineName: "INT_DTHE_PKAE", intChannelNumber: "27", intDescription: "PKAE Interrupt" },
	{ intDefineName: "INT_DTHE_SHA_S", intChannelNumber: "28", intDescription: "SHA_S Interrupt" },
	{ intDefineName: "INT_DTHE_SHA_P", intChannelNumber: "29", intDescription: "SHA_P Interrupt" },
	{ intDefineName: "INT_DTHE_AES_S", intChannelNumber: "30", intDescription: "AES_S Interrupt" },
	{ intDefineName: "INT_DTHE_AES_P", intChannelNumber: "31", intDescription: "AES_P Interrupt" },
	{ intDefineName: "INT_DTHE_SM3", intChannelNumber: "32", intDescription: "SM3 Interrupt" },
	{ intDefineName: "INT_DTHE_SM4", intChannelNumber: "33", intDescription: "SM4 Interrupt" },
	{ intDefineName: "INT_FLC1", intChannelNumber: "34", intDescription: "Flash Controller Interrupt 1" },
	{ intDefineName: "INT_FLC2", intChannelNumber: "35", intDescription: "Flash Controller Interrupt 2" },
	{ intDefineName: "INT_EPWM1", intChannelNumber: "36", intDescription: "EPWM1 Interrupt" },
	{ intDefineName: "INT_EPWM1_TZ", intChannelNumber: "37", intDescription: "EPWM1 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM2", intChannelNumber: "38", intDescription: "EPWM2 Interrupt" },
	{ intDefineName: "INT_EPWM2_TZ", intChannelNumber: "39", intDescription: "EPWM2 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM3", intChannelNumber: "40", intDescription: "EPWM3 Interrupt" },
	{ intDefineName: "INT_EPWM3_TZ", intChannelNumber: "41", intDescription: "EPWM3 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM4", intChannelNumber: "42", intDescription: "EPWM4 Interrupt" },
	{ intDefineName: "INT_EPWM4_TZ", intChannelNumber: "43", intDescription: "EPWM4 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM5", intChannelNumber: "44", intDescription: "EPWM5 Interrupt" },
	{ intDefineName: "INT_EPWM5_TZ", intChannelNumber: "45", intDescription: "EPWM5 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM6", intChannelNumber: "46", intDescription: "EPWM6 Interrupt" },
	{ intDefineName: "INT_EPWM6_TZ", intChannelNumber: "47", intDescription: "EPWM6 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM7", intChannelNumber: "48", intDescription: "EPWM7 Interrupt" },
	{ intDefineName: "INT_EPWM7_TZ", intChannelNumber: "49", intDescription: "EPWM7 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM8", intChannelNumber: "50", intDescription: "EPWM8 Interrupt" },
	{ intDefineName: "INT_EPWM8_TZ", intChannelNumber: "51", intDescription: "EPWM8 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM9", intChannelNumber: "52", intDescription: "EPWM9 Interrupt" },
	{ intDefineName: "INT_EPWM9_TZ", intChannelNumber: "53", intDescription: "EPWM9 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM10", intChannelNumber: "54", intDescription: "EPWM10 Interrupt" },
	{ intDefineName: "INT_EPWM10_TZ", intChannelNumber: "55", intDescription: "EPWM10 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM11", intChannelNumber: "56", intDescription: "EPWM11 Interrupt" },
	{ intDefineName: "INT_EPWM11_TZ", intChannelNumber: "57", intDescription: "EPWM11 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM12", intChannelNumber: "58", intDescription: "EPWM12 Interrupt" },
	{ intDefineName: "INT_EPWM12_TZ", intChannelNumber: "59", intDescription: "EPWM12 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM13", intChannelNumber: "60", intDescription: "EPWM13 Interrupt" },
	{ intDefineName: "INT_EPWM13_TZ", intChannelNumber: "61", intDescription: "EPWM13 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM14", intChannelNumber: "62", intDescription: "EPWM14 Interrupt" },
	{ intDefineName: "INT_EPWM14_TZ", intChannelNumber: "63", intDescription: "EPWM14 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM15", intChannelNumber: "64", intDescription: "EPWM15 Interrupt" },
	{ intDefineName: "INT_EPWM15_TZ", intChannelNumber: "65", intDescription: "EPWM15 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM16", intChannelNumber: "66", intDescription: "EPWM16 Interrupt" },
	{ intDefineName: "INT_EPWM16_TZ", intChannelNumber: "67", intDescription: "EPWM16 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM17", intChannelNumber: "68", intDescription: "EPWM17 Interrupt" },
	{ intDefineName: "INT_EPWM17_TZ", intChannelNumber: "69", intDescription: "EPWM17 Trip Zone Interrupt" },
	{ intDefineName: "INT_EPWM18", intChannelNumber: "70", intDescription: "EPWM18 Interrupt" },
	{ intDefineName: "INT_EPWM18_TZ", intChannelNumber: "71", intDescription: "EPWM18 Trip Zone Interrupt" },
	{ intDefineName: "INT_EQEP1", intChannelNumber: "72", intDescription: "EQEP1 Interrupt" },
	{ intDefineName: "INT_EQEP2", intChannelNumber: "73", intDescription: "EQEP2 Interrupt" },
	{ intDefineName: "INT_EQEP3", intChannelNumber: "74", intDescription: "EQEP3 Interrupt" },
	{ intDefineName: "INT_EQEP4", intChannelNumber: "75", intDescription: "EQEP4 Interrupt" },
	{ intDefineName: "INT_EQEP5", intChannelNumber: "76", intDescription: "EQEP5 Interrupt" },
	{ intDefineName: "INT_EQEP6", intChannelNumber: "77", intDescription: "EQEP6 Interrupt" },
	{ intDefineName: "INT_ECAP1", intChannelNumber: "78", intDescription: "ECAP1 Interrupt" },
	{ intDefineName: "INT_ECAP2", intChannelNumber: "79", intDescription: "ECAP2 Interrupt" },
	{ intDefineName: "INT_ECAP3", intChannelNumber: "80", intDescription: "ECAP3 Interrupt" },
	{ intDefineName: "INT_ECAP4", intChannelNumber: "81", intDescription: "ECAP4 Interrupt" },
	{ intDefineName: "INT_ECAP5", intChannelNumber: "82", intDescription: "ECAP5 Interrupt" },
	{ intDefineName: "INT_HRCAP5", intChannelNumber: "83", intDescription: "HRCAP5 Interrupt" },
	{ intDefineName: "INT_ECAP6", intChannelNumber: "84", intDescription: "ECAP6 Interrupt" },
	{ intDefineName: "INT_HRCAP6", intChannelNumber: "85", intDescription: "HRCAP6 Interrupt" },
	{ intDefineName: "INT_ADCA_EVT", intChannelNumber: "86", intDescription: "ADCA Event Interrupt" },
	{ intDefineName: "INT_ADCA1", intChannelNumber: "87", intDescription: "ADCA Interrupt 1" },
	{ intDefineName: "INT_ADCA2", intChannelNumber: "88", intDescription: "ADCA Interrupt 2" },
	{ intDefineName: "INT_ADCA3", intChannelNumber: "89", intDescription: "ADCA Interrupt 3" },
	{ intDefineName: "INT_ADCA4", intChannelNumber: "90", intDescription: "ADCA Interrupt 4" },
	{ intDefineName: "INT_ADCB_EVT", intChannelNumber: "91", intDescription: "ADCB Event Interrupt" },
	{ intDefineName: "INT_ADCB1", intChannelNumber: "92", intDescription: "ADCB Interrupt 1" },
	{ intDefineName: "INT_ADCB2", intChannelNumber: "93", intDescription: "ADCB Interrupt 2" },
	{ intDefineName: "INT_ADCB3", intChannelNumber: "94", intDescription: "ADCB Interrupt 3" },
	{ intDefineName: "INT_ADCB4", intChannelNumber: "95", intDescription: "ADCB Interrupt 4" },
	{ intDefineName: "INT_ADCC_EVT", intChannelNumber: "96", intDescription: "ADCC Event Interrupt" },
	{ intDefineName: "INT_ADCC1", intChannelNumber: "97", intDescription: "ADCC Interrupt 1" },
	{ intDefineName: "INT_ADCC2", intChannelNumber: "98", intDescription: "ADCC Interrupt 2" },
	{ intDefineName: "INT_ADCC3", intChannelNumber: "99", intDescription: "ADCC Interrupt 3" },
	{ intDefineName: "INT_ADCC4", intChannelNumber: "100", intDescription: "ADCC Interrupt 4" },
	{ intDefineName: "INT_ADCD_EVT", intChannelNumber: "101", intDescription: "ADCD Event Interrupt" },
	{ intDefineName: "INT_ADCD1", intChannelNumber: "102", intDescription: "ADCD Interrupt 1" },
	{ intDefineName: "INT_ADCD2", intChannelNumber: "103", intDescription: "ADCD Interrupt 2" },
	{ intDefineName: "INT_ADCD3", intChannelNumber: "104", intDescription: "ADCD Interrupt 3" },
	{ intDefineName: "INT_ADCD4", intChannelNumber: "105", intDescription: "ADCD Interrupt 4" },
	{ intDefineName: "INT_ADCE_EVT", intChannelNumber: "106", intDescription: "ADCE Event Interrupt" },
	{ intDefineName: "INT_ADCE1", intChannelNumber: "107", intDescription: "ADCE Interrupt 1" },
	{ intDefineName: "INT_ADCE2", intChannelNumber: "108", intDescription: "ADCE Interrupt 2" },
	{ intDefineName: "INT_ADCE3", intChannelNumber: "109", intDescription: "ADCE Interrupt 3" },
	{ intDefineName: "INT_ADCE4", intChannelNumber: "110", intDescription: "ADCE Interrupt 4" },
	{ intDefineName: "INT_SD1_ERR", intChannelNumber: "112", intDescription: "SDFM 1 Error Interrupt" },
	{ intDefineName: "INT_SD1_FLT1_DR", intChannelNumber: "113", intDescription: "SDFM 1 Filter 1 Interrupt" },
	{ intDefineName: "INT_SD1_FLT2_DR", intChannelNumber: "114", intDescription: "SDFM 1 Filter 2 Interrupt" },
	{ intDefineName: "INT_SD1_FLT3_DR", intChannelNumber: "115", intDescription: "SDFM 1 Filter 3 Interrupt" },
	{ intDefineName: "INT_SD1_FLT4_DR", intChannelNumber: "116", intDescription: "SDFM 1 Filter 4 Interrupt" },
	{ intDefineName: "INT_SD2_ERR", intChannelNumber: "117", intDescription: "SDFM 1 Error Interrupt" },
	{ intDefineName: "INT_SD2_FLT1_DR", intChannelNumber: "118", intDescription: "SDFM 1 Filter 1 Interrupt" },
	{ intDefineName: "INT_SD2_FLT2_DR", intChannelNumber: "119", intDescription: "SDFM 1 Filter 2 Interrupt" },
	{ intDefineName: "INT_SD2_FLT3_DR", intChannelNumber: "120", intDescription: "SDFM 1 Filter 3 Interrupt" },
	{ intDefineName: "INT_SD2_FLT4_DR", intChannelNumber: "121", intDescription: "SDFM 1 Filter 4 Interrupt" },
	{ intDefineName: "INT_SD3_ERR", intChannelNumber: "122", intDescription: "SDFM 1 Error Interrupt" },
	{ intDefineName: "INT_SD3_FLT1_DR", intChannelNumber: "123", intDescription: "SDFM 1 Filter 1 Interrupt" },
	{ intDefineName: "INT_SD3_FLT2_DR", intChannelNumber: "124", intDescription: "SDFM 1 Filter 2 Interrupt" },
	{ intDefineName: "INT_SD3_FLT3_DR", intChannelNumber: "125", intDescription: "SDFM 1 Filter 3 Interrupt" },
	{ intDefineName: "INT_SD3_FLT4_DR", intChannelNumber: "126", intDescription: "SDFM 1 Filter 4 Interrupt" },
	{ intDefineName: "INT_SD4_ERR", intChannelNumber: "127", intDescription: "SDFM 1 Error Interrupt" },
	{ intDefineName: "INT_SD4_FLT1_DR", intChannelNumber: "128", intDescription: "SDFM 1 Filter 1 Interrupt" },
	{ intDefineName: "INT_SD4_FLT2_DR", intChannelNumber: "129", intDescription: "SDFM 1 Filter 2 Interrupt" },
	{ intDefineName: "INT_SD4_FLT3_DR", intChannelNumber: "130", intDescription: "SDFM 1 Filter 3 Interrupt" },
	{ intDefineName: "INT_SD4_FLT4_DR", intChannelNumber: "131", intDescription: "SDFM 1 Filter 4 Interrupt" },
	{ intDefineName: "INT_CLB1", intChannelNumber: "132", intDescription: "CLB1 Interrupt" },
	{ intDefineName: "INT_CLB2", intChannelNumber: "133", intDescription: "CLB2 Interrupt" },
	{ intDefineName: "INT_CLB3", intChannelNumber: "134", intDescription: "CLB3 Interrupt" },
	{ intDefineName: "INT_CLB4", intChannelNumber: "135", intDescription: "CLB4 Interrupt" },
	{ intDefineName: "INT_CLB5", intChannelNumber: "136", intDescription: "CLB5 Interrupt" },
	{ intDefineName: "INT_CLB6", intChannelNumber: "137", intDescription: "CLB6 Interrupt" },
	{ intDefineName: "INT_UARTA", intChannelNumber: "138", intDescription: "UARTA Interrupt" },
	{ intDefineName: "INT_UARTB", intChannelNumber: "139", intDescription: "UARTB Interrupt" },
	{ intDefineName: "INT_UARTC", intChannelNumber: "140", intDescription: "UARTC Interrupt" },
	{ intDefineName: "INT_UARTD", intChannelNumber: "141", intDescription: "UARTD Interrupt" },
	{ intDefineName: "INT_UARTE", intChannelNumber: "142", intDescription: "UARTE Interrupt" },
	{ intDefineName: "INT_UARTF", intChannelNumber: "143", intDescription: "UARTF Interrupt" },
	{ intDefineName: "INT_LINA_0", intChannelNumber: "144", intDescription: "LINA Interrupt 0" },
	{ intDefineName: "INT_LINA_1", intChannelNumber: "145", intDescription: "LINA Interrupt 1" },
	{ intDefineName: "INT_LINB_0", intChannelNumber: "146", intDescription: "LINB Interrupt 0" },
	{ intDefineName: "INT_LINB_1", intChannelNumber: "147", intDescription: "LINB Interrupt 1" },
	{ intDefineName: "INT_PMBUSA", intChannelNumber: "148", intDescription: "PMBUSA Interrupt" },
	{ intDefineName: "INT_I2CA", intChannelNumber: "149", intDescription: "I2CA Interrupt 1" },
	{ intDefineName: "INT_I2CA_FIFO", intChannelNumber: "150", intDescription: "I2CA Interrupt 2" },
	{ intDefineName: "INT_I2CB", intChannelNumber: "151", intDescription: "I2CB Interrupt 1" },
	{ intDefineName: "INT_I2CB_FIFO", intChannelNumber: "152", intDescription: "I2CB Interrupt 2" },
	{ intDefineName: "INT_SPIA_TX", intChannelNumber: "153", intDescription: "SPIA TX Interrupt" },
	{ intDefineName: "INT_SPIA_RX", intChannelNumber: "154", intDescription: "SPIA RX Interrupt" },
	{ intDefineName: "INT_SPIB_TX", intChannelNumber: "155", intDescription: "SPIB TX Interrupt" },
	{ intDefineName: "INT_SPIB_RX", intChannelNumber: "156", intDescription: "SPIB RX Interrupt" },
	{ intDefineName: "INT_SPIC_TX", intChannelNumber: "157", intDescription: "SPIC TX Interrupt" },
	{ intDefineName: "INT_SPIC_RX", intChannelNumber: "158", intDescription: "SPIC RX Interrupt" },
	{ intDefineName: "INT_SPID_TX", intChannelNumber: "159", intDescription: "SPID TX Interrupt" },
	{ intDefineName: "INT_SPID_RX", intChannelNumber: "160", intDescription: "SPID RX Interrupt" },
	{ intDefineName: "INT_SPIE_TX", intChannelNumber: "161", intDescription: "SPIE TX Interrupt" },
	{ intDefineName: "INT_SPIE_RX", intChannelNumber: "162", intDescription: "SPIE RX Interrupt" },
	{ intDefineName: "INT_FSITXA1", intChannelNumber: "163", intDescription: "FSITXA Interrupt 1" },
	{ intDefineName: "INT_FSITXA2", intChannelNumber: "164", intDescription: "FSITXA Interrupt 2" },
	{ intDefineName: "INT_FSITXB1", intChannelNumber: "165", intDescription: "FSITXB Interrupt 1" },
	{ intDefineName: "INT_FSITXB2", intChannelNumber: "166", intDescription: "FSITXB Interrupt 2" },
	{ intDefineName: "INT_FSITXC1", intChannelNumber: "167", intDescription: "FSITXC Interrupt 1" },
	{ intDefineName: "INT_FSITXC2", intChannelNumber: "168", intDescription: "FSITXC Interrupt 2" },
	{ intDefineName: "INT_FSITXD1", intChannelNumber: "169", intDescription: "FSITXD Interrupt 1" },
	{ intDefineName: "INT_FSITXD2", intChannelNumber: "170", intDescription: "FSITXD Interrupt 2" },
	{ intDefineName: "INT_FSIRXA1", intChannelNumber: "171", intDescription: "FSIRXA Interrupt 1" },
	{ intDefineName: "INT_FSIRXA2", intChannelNumber: "172", intDescription: "FSIRXA Interrupt 2" },
	{ intDefineName: "INT_FSIRXB1", intChannelNumber: "173", intDescription: "FSIRXB Interrupt 1" },
	{ intDefineName: "INT_FSIRXB2", intChannelNumber: "174", intDescription: "FSIRXB Interrupt 2" },
	{ intDefineName: "INT_FSIRXC1", intChannelNumber: "175", intDescription: "FSIRXC Interrupt 1" },
	{ intDefineName: "INT_FSIRXC2", intChannelNumber: "176", intDescription: "FSIRXC Interrupt 2" },
	{ intDefineName: "INT_FSIRXD1", intChannelNumber: "177", intDescription: "FSIRXD Interrupt 1" },
	{ intDefineName: "INT_FSIRXD2", intChannelNumber: "178", intDescription: "FSIRXD Interrupt 2" },
	{ intDefineName: "INT_SENTA", intChannelNumber: "179", intDescription: "SENTA Interrupt" },
	{ intDefineName: "INT_SENTB", intChannelNumber: "180", intDescription: "SENTB Interrupt" },
	{ intDefineName: "INT_SENTC", intChannelNumber: "181", intDescription: "SENTC Interrupt" },
	{ intDefineName: "INT_SENTD", intChannelNumber: "182", intDescription: "SENTD Interrupt" },
	{ intDefineName: "INT_SENTE", intChannelNumber: "183", intDescription: "SENTE Interrupt" },
	{ intDefineName: "INT_SENTF", intChannelNumber: "184", intDescription: "SENTF Interrupt" },
	{ intDefineName: "INT_MCANA_WAKE", intChannelNumber: "186", intDescription: "MCANA Wakeup Interrupt" },
	{ intDefineName: "INT_MCANA_1", intChannelNumber: "187", intDescription: "MCANA Interrupt 1" },
	{ intDefineName: "INT_MCANA_0", intChannelNumber: "188", intDescription: "MCANA Interrupt 0" },
	{ intDefineName: "INT_MCANB_WAKE", intChannelNumber: "190", intDescription: "MCANB Wakeup Interrupt" },
	{ intDefineName: "INT_MCANB_1", intChannelNumber: "191", intDescription: "MCANB Interrupt 1" },
	{ intDefineName: "INT_MCANB_0", intChannelNumber: "192", intDescription: "MCANB Interrupt 0" },
	{ intDefineName: "INT_MCANC_WAKE", intChannelNumber: "194", intDescription: "MCANC Wakeup Interrupt" },
	{ intDefineName: "INT_MCANC_1", intChannelNumber: "195", intDescription: "MCANC Interrupt 1" },
	{ intDefineName: "INT_MCANC_0", intChannelNumber: "196", intDescription: "MCANC Interrupt 0" },
	{ intDefineName: "INT_MCAND_WAKE", intChannelNumber: "198", intDescription: "MCAND Wakeup Interrupt" },
	{ intDefineName: "INT_MCAND_1", intChannelNumber: "199", intDescription: "MCAND Interrupt 1" },
	{ intDefineName: "INT_MCAND_0", intChannelNumber: "200", intDescription: "MCAND Interrupt 0" },
	{ intDefineName: "INT_MCANE_WAKE", intChannelNumber: "202", intDescription: "MCANE Wakeup Interrupt" },
	{ intDefineName: "INT_MCANE_1", intChannelNumber: "203", intDescription: "MCANE Interrupt 1" },
	{ intDefineName: "INT_MCANE_0", intChannelNumber: "204", intDescription: "MCANE Interrupt 0" },
	{ intDefineName: "INT_MCANF_WAKE", intChannelNumber: "206", intDescription: "MCANF Wakeup Interrupt" },
	{ intDefineName: "INT_MCANF_1", intChannelNumber: "207", intDescription: "MCANF Interrupt 1" },
	{ intDefineName: "INT_MCANF_0", intChannelNumber: "208", intDescription: "MCANF Interrupt 0" },
	{ intDefineName: "INT_ECAT", intChannelNumber: "209", intDescription: "Ethercat Main Interrupt" },
	{ intDefineName: "INT_ECATSYNC0", intChannelNumber: "210", intDescription: "Ethercat SYNC0 Interrupt" },
	{ intDefineName: "INT_ECATSYNC1", intChannelNumber: "211", intDescription: "Ethercat SYNC1 Interrupt" },
	{ intDefineName: "INT_ECATRST", intChannelNumber: "212", intDescription: "Ethercat Reset Interrupt" },
	{ intDefineName: "INT_RTDMA1CH1", intChannelNumber: "213", intDescription: "RTDMA1 Channel 1 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH2", intChannelNumber: "214", intDescription: "RTDMA1 Channel 2 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH3", intChannelNumber: "215", intDescription: "RTDMA1 Channel 3 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH4", intChannelNumber: "216", intDescription: "RTDMA1 Channel 4 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH5", intChannelNumber: "217", intDescription: "RTDMA1 Channel 5 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH6", intChannelNumber: "218", intDescription: "RTDMA1 Channel 6 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH7", intChannelNumber: "219", intDescription: "RTDMA1 Channel 7 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH8", intChannelNumber: "220", intDescription: "RTDMA1 Channel 8 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH9", intChannelNumber: "221", intDescription: "RTDMA1 Channel 9 Interrupt" },
	{ intDefineName: "INT_RTDMA1CH10", intChannelNumber: "222", intDescription: "RTDMA1 Channel 10 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH1", intChannelNumber: "223", intDescription: "RTDMA2 Channel 1 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH2", intChannelNumber: "224", intDescription: "RTDMA2 Channel 2 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH3", intChannelNumber: "225", intDescription: "RTDMA2 Channel 3 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH4", intChannelNumber: "226", intDescription: "RTDMA2 Channel 4 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH5", intChannelNumber: "227", intDescription: "RTDMA2 Channel 5 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH6", intChannelNumber: "228", intDescription: "RTDMA2 Channel 6 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH7", intChannelNumber: "229", intDescription: "RTDMA2 Channel 7 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH8", intChannelNumber: "230", intDescription: "RTDMA2 Channel 8 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH9", intChannelNumber: "231", intDescription: "RTDMA2 Channel 9 Interrupt" },
	{ intDefineName: "INT_RTDMA2CH10", intChannelNumber: "232", intDescription: "RTDMA2 Channel 10 Interrupt" },
	{ intDefineName: "INT_WADI1", intChannelNumber: "233", intDescription: "WADI1 Interrupt" },
	{ intDefineName: "INT_WADI2", intChannelNumber: "234", intDescription: "WADI2 Interrupt" },
	{ intDefineName: "INT_XINT1", intChannelNumber: "235", intDescription: "XINT1 Interrupt" },
	{ intDefineName: "INT_XINT2", intChannelNumber: "236", intDescription: "XINT2 Interrupt" },
	{ intDefineName: "INT_XINT3", intChannelNumber: "237", intDescription: "XINT3 Interrupt" },
	{ intDefineName: "INT_XINT4", intChannelNumber: "238", intDescription: "XINT4 Interrupt" },
	{ intDefineName: "INT_XINT5", intChannelNumber: "239", intDescription: "XINT5 Interrupt" },
	{ intDefineName: "INT_DCC1", intChannelNumber: "240", intDescription: "DCC1 Interrupt" },
	{ intDefineName: "INT_DCC2", intChannelNumber: "241", intDescription: "DCC2 Interrupt" },
	{ intDefineName: "INT_DCC3", intChannelNumber: "242", intDescription: "DCC3 Interrupt" },
	{ intDefineName: "INT_LPM_WAKE", intChannelNumber: "243", intDescription: "LPM Wakeup Interrupt" },
	{ intDefineName: "INT_SW12", intChannelNumber: "244", intDescription: "Software Interrupt 12" },
	{ intDefineName: "INT_SW11", intChannelNumber: "245", intDescription: "Software Interrupt 11" },
	{ intDefineName: "INT_SW10", intChannelNumber: "246", intDescription: "Software Interrupt 10" },
	{ intDefineName: "INT_SW9", intChannelNumber: "247", intDescription: "Software Interrupt 9" },
	{ intDefineName: "INT_SW8", intChannelNumber: "248", intDescription: "Software Interrupt 8" },
	{ intDefineName: "INT_SW7", intChannelNumber: "249", intDescription: "Software Interrupt 7" },
	{ intDefineName: "INT_SW6", intChannelNumber: "250", intDescription: "Software Interrupt 6" },
	{ intDefineName: "INT_SW5", intChannelNumber: "251", intDescription: "Software Interrupt 5" },
	{ intDefineName: "INT_SW4", intChannelNumber: "252", intDescription: "Software Interrupt 4" },
	{ intDefineName: "INT_SW3", intChannelNumber: "253", intDescription: "Software Interrupt 3" },
	{ intDefineName: "INT_SW2", intChannelNumber: "254", intDescription: "Software Interrupt 2" },
	{ intDefineName: "INT_SW1", intChannelNumber: "255", intDescription: "Software Interrupt 1" },
	{ intDefineName: "INT_NMI", intChannelNumber: "1024", intDescription: "" },
];
module.exports = {
	interrupts: interrupts,
}
