let PIE_REGISTERS = [
	{ name: "CTRL", description: "ePIE Control Register", offset: "0x0", size: "16",
		bits: [
			{ name: "ENPIE", description: "PIE Enable", size: "1", shift: "0", mask: "0x1" },
			{ name: "PIEVECT", description: "PIE Vector Address", size: "15", shift: "1", mask: "0xFFFE" },
		]
	},
	{ name: "ACK", description: "Interrupt Acknowledge Register", offset: "0x1", size: "16",
		bits: [
			{ name: "ACK1", description: "Acknowledge PIE Interrupt Group 1", size: "1", shift: "0", mask: "0x1" },
			{ name: "ACK2", description: "Acknowledge PIE Interrupt Group 2", size: "1", shift: "1", mask: "0x2" },
			{ name: "ACK3", description: "Acknowledge PIE Interrupt Group 3", size: "1", shift: "2", mask: "0x4" },
			{ name: "ACK4", description: "Acknowledge PIE Interrupt Group 4", size: "1", shift: "3", mask: "0x8" },
			{ name: "ACK5", description: "Acknowledge PIE Interrupt Group 5", size: "1", shift: "4", mask: "0x10" },
			{ name: "ACK6", description: "Acknowledge PIE Interrupt Group 6", size: "1", shift: "5", mask: "0x20" },
			{ name: "ACK7", description: "Acknowledge PIE Interrupt Group 7", size: "1", shift: "6", mask: "0x40" },
			{ name: "ACK8", description: "Acknowledge PIE Interrupt Group 8", size: "1", shift: "7", mask: "0x80" },
			{ name: "ACK9", description: "Acknowledge PIE Interrupt Group 9", size: "1", shift: "8", mask: "0x100" },
			{ name: "ACK10", description: "Acknowledge PIE Interrupt Group 10", size: "1", shift: "9", mask: "0x200" },
			{ name: "ACK11", description: "Acknowledge PIE Interrupt Group 11", size: "1", shift: "10", mask: "0x400" },
			{ name: "ACK12", description: "Acknowledge PIE Interrupt Group 12", size: "1", shift: "11", mask: "0x800" },
		]
	},
	{ name: "IER1", description: "Interrupt Group 1 Enable Register", offset: "0x2", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 1.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 1.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 1.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 1.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 1.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 1.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 1.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 1.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 1.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 1.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 1.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 1.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 1.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 1.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 1.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 1.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR1", description: "Interrupt Group 1 Flag Register", offset: "0x3", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 1.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 1.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 1.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 1.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 1.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 1.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 1.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 1.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 1.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 1.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 1.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 1.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 1.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 1.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 1.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 1.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER2", description: "Interrupt Group 2 Enable Register", offset: "0x4", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 2.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 2.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 2.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 2.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 2.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 2.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 2.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 2.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 2.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 2.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 2.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 2.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 2.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 2.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 2.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 2.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR2", description: "Interrupt Group 2 Flag Register", offset: "0x5", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 2.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 2.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 2.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 2.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 2.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 2.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 2.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 2.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 2.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 2.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 2.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 2.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 2.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 2.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 2.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 2.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER3", description: "Interrupt Group 3 Enable Register", offset: "0x6", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 3.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 3.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 3.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 3.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 3.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 3.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 3.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 3.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 3.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 3.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 3.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 3.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 3.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 3.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 3.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 3.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR3", description: "Interrupt Group 3 Flag Register", offset: "0x7", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 3.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 3.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 3.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 3.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 3.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 3.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 3.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 3.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 3.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 3.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 3.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 3.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 3.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 3.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 3.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 3.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER4", description: "Interrupt Group 4 Enable Register", offset: "0x8", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 4.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 4.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 4.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 4.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 4.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 4.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 4.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 4.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 4.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 4.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 4.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 4.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 4.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 4.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 4.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 4.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR4", description: "Interrupt Group 4 Flag Register", offset: "0x9", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 4.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 4.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 4.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 4.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 4.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 4.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 4.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 4.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 4.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 4.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 4.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 4.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 4.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 4.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 4.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 4.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER5", description: "Interrupt Group 5 Enable Register", offset: "0xA", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 5.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 5.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 5.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 5.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 5.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 5.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 5.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 5.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 5.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 5.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 5.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 5.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 5.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 5.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 5.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 5.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR5", description: "Interrupt Group 5 Flag Register", offset: "0xB", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 5.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 5.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 5.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 5.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 5.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 5.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 5.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 5.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 5.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 5.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 5.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 5.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 5.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 5.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 5.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 5.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER6", description: "Interrupt Group 6 Enable Register", offset: "0xC", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 6.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 6.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 6.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 6.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 6.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 6.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 6.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 6.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 6.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 6.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 6.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 6.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 6.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 6.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 6.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 6.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR6", description: "Interrupt Group 6 Flag Register", offset: "0xD", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 6.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 6.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 6.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 6.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 6.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 6.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 6.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 6.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 6.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 6.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 6.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 6.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 6.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 6.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 6.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 6.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER7", description: "Interrupt Group 7 Enable Register", offset: "0xE", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 7.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 7.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 7.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 7.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 7.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 7.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 7.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 7.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 7.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 7.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 7.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 7.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 7.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 7.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 7.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 7.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR7", description: "Interrupt Group 7 Flag Register", offset: "0xF", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 7.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 7.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 7.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 7.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 7.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 7.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 7.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 7.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 7.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 7.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 7.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 7.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 7.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 7.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 7.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 7.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER8", description: "Interrupt Group 8 Enable Register", offset: "0x10", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 8.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 8.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 8.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 8.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 8.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 8.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 8.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 8.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 8.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 8.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 8.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 8.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 8.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 8.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 8.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 8.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR8", description: "Interrupt Group 8 Flag Register", offset: "0x11", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 8.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 8.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 8.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 8.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 8.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 8.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 8.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 8.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 8.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 8.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 8.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 8.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 8.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 8.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 8.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 8.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER9", description: "Interrupt Group 9 Enable Register", offset: "0x12", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 9.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 9.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 9.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 9.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 9.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 9.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 9.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 9.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 9.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 9.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 9.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 9.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 9.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 9.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 9.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 9.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR9", description: "Interrupt Group 9 Flag Register", offset: "0x13", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 9.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 9.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 9.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 9.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 9.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 9.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 9.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 9.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 9.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 9.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 9.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 9.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 9.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 9.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 9.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 9.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER10", description: "Interrupt Group 10 Enable Register", offset: "0x14", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 10.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 10.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 10.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 10.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 10.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 10.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 10.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 10.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 10.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 10.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 10.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 10.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 10.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 10.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 10.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 10.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR10", description: "Interrupt Group 10 Flag Register", offset: "0x15", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 10.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 10.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 10.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 10.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 10.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 10.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 10.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 10.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 10.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 10.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 10.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 10.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 10.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 10.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 10.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 10.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER11", description: "Interrupt Group 11 Enable Register", offset: "0x16", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 11.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 11.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 11.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 11.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 11.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 11.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 11.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 11.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 11.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 11.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 11.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 11.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 11.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 11.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 11.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 11.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR11", description: "Interrupt Group 11 Flag Register", offset: "0x17", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 11.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 11.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 11.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 11.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 11.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 11.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 11.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 11.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 11.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 11.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 11.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 11.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 11.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 11.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 11.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 11.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IER12", description: "Interrupt Group 12 Enable Register", offset: "0x18", size: "16",
		bits: [
			{ name: "INTX1", description: "Enable for Interrupt 12.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Enable for Interrupt 12.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Enable for Interrupt 12.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Enable for Interrupt 12.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Enable for Interrupt 12.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Enable for Interrupt 12.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Enable for Interrupt 12.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Enable for Interrupt 12.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Enable for Interrupt 12.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Enable for Interrupt 12.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Enable for Interrupt 12.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Enable for Interrupt 12.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Enable for Interrupt 12.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Enable for Interrupt 12.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Enable for Interrupt 12.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Enable for Interrupt 12.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "IFR12", description: "Interrupt Group 12 Flag Register", offset: "0x19", size: "16",
		bits: [
			{ name: "INTX1", description: "Flag for Interrupt 12.1", size: "1", shift: "0", mask: "0x1" },
			{ name: "INTX2", description: "Flag for Interrupt 12.2", size: "1", shift: "1", mask: "0x2" },
			{ name: "INTX3", description: "Flag for Interrupt 12.3", size: "1", shift: "2", mask: "0x4" },
			{ name: "INTX4", description: "Flag for Interrupt 12.4", size: "1", shift: "3", mask: "0x8" },
			{ name: "INTX5", description: "Flag for Interrupt 12.5", size: "1", shift: "4", mask: "0x10" },
			{ name: "INTX6", description: "Flag for Interrupt 12.6", size: "1", shift: "5", mask: "0x20" },
			{ name: "INTX7", description: "Flag for Interrupt 12.7", size: "1", shift: "6", mask: "0x40" },
			{ name: "INTX8", description: "Flag for Interrupt 12.8", size: "1", shift: "7", mask: "0x80" },
			{ name: "INTX9", description: "Flag for Interrupt 12.9", size: "1", shift: "8", mask: "0x100" },
			{ name: "INTX10", description: "Flag for Interrupt 12.10", size: "1", shift: "9", mask: "0x200" },
			{ name: "INTX11", description: "Flag for Interrupt 12.11", size: "1", shift: "10", mask: "0x400" },
			{ name: "INTX12", description: "Flag for Interrupt 12.12", size: "1", shift: "11", mask: "0x800" },
			{ name: "INTX13", description: "Flag for Interrupt 12.13", size: "1", shift: "12", mask: "0x1000" },
			{ name: "INTX14", description: "Flag for Interrupt 12.14", size: "1", shift: "13", mask: "0x2000" },
			{ name: "INTX15", description: "Flag for Interrupt 12.15", size: "1", shift: "14", mask: "0x4000" },
			{ name: "INTX16", description: "Flag for Interrupt 12.16", size: "1", shift: "15", mask: "0x8000" },
		]
	},
];
module.exports = {
	pieRegisters: PIE_REGISTERS,
}
