let TRIGXBAR_REGISTERS = [
	{ name: "SYNCSELECT", description: "Sync Input and Output Select Register", offset: "0x0", size: "16",
		bits: [
		]
	},
	{ name: "ADCSOCOUTSELECT", description: "External ADC (Off Chip) SOC Select Register", offset: "0x2", size: "16",
		bits: [
		]
	},
	{ name: "SYNCSOCLOCK", description: "SYNCSEL and EXTADCSOC Select Lock register", offset: "0x4", size: "16",
		bits: [
			{ name: "XBAR_SYNCSELECT_EPWM4SYNCIN", description: "Selects Sync Input Source for EPWM4", size: "3", shift: "0", mask: "0x7" },
			{ name: "XBAR_SYNCSELECT_EPWM7SYNCIN", description: "Selects Sync Input Source for EPWM7", size: "3", shift: "3", mask: "0x38" },
			{ name: "XBAR_SYNCSELECT_EPWM10SYNCIN", description: "Selects Sync Input Source for EPWM10", size: "3", shift: "6", mask: "0x1C0" },
			{ name: "XBAR_SYNCSELECT_ECAP1SYNCIN", description: "Selects Sync Input Source for ECAP1", size: "3", shift: "9", mask: "0xE00" },
			{ name: "XBAR_SYNCSELECT_ECAP4SYNCIN", description: "Selects Sync Input Source for ECAP4", size: "3", shift: "12", mask: "0x7000" },
			{ name: "XBAR_SYNCSELECT_ECAP7SYNCIN", description: "Selects Sync Input Source for ECAP7", size: "4", shift: "16", mask: "0xF0000" },
			{ name: "XBAR_SYNCSELECT_EPWM13SYNCIN", description: "Selects Sync Input Source for EPWM13", size: "4", shift: "20", mask: "0xF00000" },
			{ name: "XBAR_SYNCSELECT_SYNCOUT1", description: "Select Syncout Source", size: "3", shift: "24", mask: "0x7000000" },
			{ name: "XBAR_SYNCSELECT_SYNCOUT", description: "Select Syncout Source", size: "2", shift: "27", mask: "0x18000000" },
			{ name: "XBAR_SYNCSELECT_EPWM1SYNCIN", description: "Selects Sync Input Source for EPWM1", size: "3", shift: "29", mask: "0xE0000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM1SOCAEN", description: "PWM1SOCAEN Enable for ADCSOCAOn", size: "1", shift: "0", mask: "0x1" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM2SOCAEN", description: "PWM2SOCAEN Enable for ADCSOCAOn", size: "1", shift: "1", mask: "0x2" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM3SOCAEN", description: "PWM3SOCAEN Enable for ADCSOCAOn", size: "1", shift: "2", mask: "0x4" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM4SOCAEN", description: "PWM4SOCAEN Enable for ADCSOCAOn", size: "1", shift: "3", mask: "0x8" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM5SOCAEN", description: "PWM5SOCAEN Enable for ADCSOCAOn", size: "1", shift: "4", mask: "0x10" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM6SOCAEN", description: "PWM6SOCAEN Enable for ADCSOCAOn", size: "1", shift: "5", mask: "0x20" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM7SOCAEN", description: "PWM7SOCAEN Enable for ADCSOCAOn", size: "1", shift: "6", mask: "0x40" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM8SOCAEN", description: "PWM8SOCAEN Enable for ADCSOCAOn", size: "1", shift: "7", mask: "0x80" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM9SOCAEN", description: "PWM9SOCAEN Enable for ADCSOCAOn", size: "1", shift: "8", mask: "0x100" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM10SOCAEN", description: "PWM10SOCAEN Enable for ADCSOCAOn", size: "1", shift: "9", mask: "0x200" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM11SOCAEN", description: "PWM11SOCAEN Enable for ADCSOCAOn", size: "1", shift: "10", mask: "0x400" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM12SOCAEN", description: "PWM12SOCAEN Enable for ADCSOCAOn", size: "1", shift: "11", mask: "0x800" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM13SOCAEN", description: "PWM13SOCAEN Enable for ADCSOCAOn", size: "1", shift: "12", mask: "0x1000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM14SOCAEN", description: "PWM14SOCAEN Enable for ADCSOCAOn", size: "1", shift: "13", mask: "0x2000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM15SOCAEN", description: "PWM15SOCAEN Enable for ADCSOCAOn", size: "1", shift: "14", mask: "0x4000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM16SOCAEN", description: "PWM16SOCAEN Enable for ADCSOCAOn", size: "1", shift: "15", mask: "0x8000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM1SOCBEN", description: "PWM1SOCBEN Enable for ADCSOCBOn", size: "1", shift: "16", mask: "0x10000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM2SOCBEN", description: "PWM2SOCBEN Enable for ADCSOCBOn", size: "1", shift: "17", mask: "0x20000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM3SOCBEN", description: "PWM3SOCBEN Enable for ADCSOCBOn", size: "1", shift: "18", mask: "0x40000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM4SOCBEN", description: "PWM4SOCBEN Enable for ADCSOCBOn", size: "1", shift: "19", mask: "0x80000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM5SOCBEN", description: "PWM5SOCBEN Enable for ADCSOCBOn", size: "1", shift: "20", mask: "0x100000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM6SOCBEN", description: "PWM6SOCBEN Enable for ADCSOCBOn", size: "1", shift: "21", mask: "0x200000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM7SOCBEN", description: "PWM7SOCBEN Enable for ADCSOCBOn", size: "1", shift: "22", mask: "0x400000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM8SOCBEN", description: "PWM8SOCBEN Enable for ADCSOCBOn", size: "1", shift: "23", mask: "0x800000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM9SOCBEN", description: "PWM9SOCBEN Enable for ADCSOCBOn", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM10SOCBEN", description: "PWM10SOCBEN Enable for ADCSOCBOn", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM11SOCBEN", description: "PWM11SOCBEN Enable for ADCSOCBOn", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM12SOCBEN", description: "PWM12SOCBEN Enable for ADCSOCBOn", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM13SOCBEN", description: "PWM13SOCBEN Enable for ADCSOCBOn", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM14SOCBEN", description: "PWM14SOCBEN Enable for ADCSOCBOn", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM15SOCBEN", description: "PWM15SOCBEN Enable for ADCSOCBOn", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "XBAR_ADCSOCOUTSELECT_PWM16SOCBEN", description: "PWM16SOCBEN Enable for ADCSOCBOn", size: "1", shift: "31", mask: "0x80000000" },
			{ name: "SYNCSELECT", description: "SYNCSEL Register Lock bit", size: "1", shift: "0", mask: "0x1" },
			{ name: "EXTADCSOCSELECT", description: "EXTADCSOCSEL Register Lock bit", size: "1", shift: "1", mask: "0x2" },
		]
	},
];
module.exports = {
	trigxbarRegisters: TRIGXBAR_REGISTERS,
}
