let MCAN_REGISTERS = [
	{ name: "SS_PID", description: "MCAN Subsystem Revision Register", offset: "0x0", size: "32",
		bits: [
			{ name: "MINOR", description: "Minor Revision", size: "6", shift: "0", mask: "0x3F" },
			{ name: "MAJOR", description: "Major Revision", size: "3", shift: "8", mask: "0x700" },
			{ name: "MODULE_ID", description: "Module Identification Number", size: "12", shift: "16", mask: "0xFFF0000" },
			{ name: "SCHEME", description: "PID Register Scheme", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "SS_CTRL", description: "MCAN Subsystem Control Register", offset: "0x2", size: "16",
		bits: [
			{ name: "DBGSUSP_FREE", description: "Debug Suspend Free", size: "1", shift: "3", mask: "0x8" },
			{ name: "WAKEUPREQEN", description: "Wakeup Request Enable", size: "1", shift: "4", mask: "0x10" },
			{ name: "AUTOWAKEUP", description: "Automatic Wakeup Enable", size: "1", shift: "5", mask: "0x20" },
			{ name: "EXT_TS_CNTR_EN", description: "External Timestamp Counter Enable", size: "1", shift: "6", mask: "0x40" },
		]
	},
	{ name: "SS_STAT", description: "MCAN Subsystem Status Register", offset: "0x4", size: "16",
		bits: [
			{ name: "RESET", description: "Soft Reset Status", size: "1", shift: "0", mask: "0x1" },
			{ name: "MEM_INIT_DONE", description: "Memory Initialization Done", size: "1", shift: "1", mask: "0x2" },
			{ name: "ENABLE_FDOE", description: "Flexible Datarate Operation Enable", size: "1", shift: "2", mask: "0x4" },
		]
	},
	{ name: "SS_ICS", description: "MCAN Subsystem Interrupt Clear Shadow Register", offset: "0x6", size: "16",
		bits: [
			{ name: "EXT_TS_CNTR_OVFL", description: "External Timestamp Counter Overflow Interrupt Status Clear", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "SS_IRS", description: "MCAN Subsystem Interrupt Raw Satus Register", offset: "0x8", size: "16",
		bits: [
			{ name: "EXT_TS_CNTR_OVFL", description: "External Timestamp Counter Overflow Interrupt Status", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "SS_IECS", description: "MCAN Subsystem Interrupt Enable Clear Shadow Register", offset: "0xA", size: "16",
		bits: [
			{ name: "EXT_TS_CNTR_OVFL", description: "External Timestamp Counter Overflow Interrupt Enable Clear", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "SS_IE", description: "MCAN Subsystem Interrupt Enable Register", offset: "0xC", size: "16",
		bits: [
			{ name: "EXT_TS_CNTR_OVFL", description: "External Timestamp Counter Overflow Interrupt Enable", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "SS_IES", description: "MCAN Subsystem Interrupt Enable Status", offset: "0xE", size: "16",
		bits: [
			{ name: "EXT_TS_CNTR_OVFL", description: "External Timestamp Counter Overflow Interrupt Enable Status", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "SS_EOI", description: "MCAN Subsystem End of Interrupt", offset: "0x10", size: "16",
		bits: [
			{ name: "EOI", description: "External Timestamp Counter Overflow End of Interrupt", size: "8", shift: "0", mask: "0xFF" },
		]
	},
	{ name: "SS_EXT_TS_PRESCALER", description: "MCAN Subsystem External Timestamp Prescaler 0", offset: "0x12", size: "32",
		bits: [
			{ name: "PRESCALER", description: "External Timestamp Prescaler", size: "24", shift: "0", mask: "0xFFFFFF" },
		]
	},
	{ name: "SS_EXT_TS_UNSERVICED_INTR_CNTR", description: "MCAN Subsystem External Timestamp Unserviced Interrupts Counter", offset: "0x14", size: "16",
		bits: [
			{ name: "EXT_TS_INTR_CNTR", description: "External Timestamp Counter Unserviced Rollover", size: "5", shift: "0", mask: "0x1F" },
		]
	},
	{ name: "CREL", description: "MCAN Core Release Register", offset: "0x0", size: "32",
		bits: [
			{ name: "DAY", description: "Time Stamp Day", size: "8", shift: "0", mask: "0xFF" },
			{ name: "MON", description: "Time Stamp Month", size: "8", shift: "8", mask: "0xFF00" },
			{ name: "YEAR", description: "Time Stamp Year", size: "4", shift: "16", mask: "0xF0000" },
			{ name: "SUBSTEP", description: "Sub-Step of Core Release", size: "4", shift: "20", mask: "0xF00000" },
			{ name: "STEP", description: "Step of Core Release", size: "4", shift: "24", mask: "0xF000000" },
			{ name: "REL", description: "Core Release", size: "4", shift: "28", mask: "0xF0000000" },
		]
	},
	{ name: "ENDN", description: "MCAN Endian Register", offset: "0x2", size: "32",
		bits: [
		]
	},
	{ name: "DBTP", description: "MCAN Data Bit Timing and Prescaler Register", offset: "0x6", size: "32",
		bits: [
			{ name: "DSJW", description: "Data Resynchronization Jump Width", size: "4", shift: "0", mask: "0xF" },
			{ name: "DTSEG2", description: "Data Time Segment After Sample Point", size: "4", shift: "4", mask: "0xF0" },
			{ name: "DTSEG1", description: "Data Time Segment Before Sample Point", size: "5", shift: "8", mask: "0x1F00" },
			{ name: "DBRP", description: "Data Bit Rate Prescaler", size: "5", shift: "16", mask: "0x1F0000" },
			{ name: "TDC", description: "Transmitter Delay Compensation", size: "1", shift: "23", mask: "0x800000" },
		]
	},
	{ name: "TEST", description: "MCAN Test Register", offset: "0x8", size: "32",
		bits: [
			{ name: "LBCK", description: "Loop Back Mode", size: "1", shift: "4", mask: "0x10" },
			{ name: "TX", description: "Control of Transmit Pin", size: "2", shift: "5", mask: "0x60" },
			{ name: "RX", description: "Receive Pin", size: "1", shift: "7", mask: "0x80" },
		]
	},
	{ name: "RWD", description: "MCAN RAM Watchdog", offset: "0xA", size: "32",
		bits: [
			{ name: "WDC", description: "Watchdog Configuration", size: "8", shift: "0", mask: "0xFF" },
			{ name: "WDV", description: "Watchdog Value", size: "8", shift: "8", mask: "0xFF00" },
		]
	},
	{ name: "CCCR", description: "MCAN CC Control Register", offset: "0xC", size: "32",
		bits: [
			{ name: "INIT", description: "Initialization", size: "1", shift: "0", mask: "0x1" },
			{ name: "CCE", description: "Configuration Change Enable", size: "1", shift: "1", mask: "0x2" },
			{ name: "ASM", description: "Restricted Operation Mode", size: "1", shift: "2", mask: "0x4" },
			{ name: "CSA", description: "Clock Stop Acknowledge", size: "1", shift: "3", mask: "0x8" },
			{ name: "CSR", description: "Clock Stop Request", size: "1", shift: "4", mask: "0x10" },
			{ name: "MON", description: "Bus Monitoring Mode", size: "1", shift: "5", mask: "0x20" },
			{ name: "DAR", description: "Disable Automatic Retransmission", size: "1", shift: "6", mask: "0x40" },
			{ name: "TEST", description: "Test Mode Enable", size: "1", shift: "7", mask: "0x80" },
			{ name: "FDOE", description: "Flexible Datarate Operation Enable", size: "1", shift: "8", mask: "0x100" },
			{ name: "BRSE", description: "Bit Rate Switch Enable", size: "1", shift: "9", mask: "0x200" },
			{ name: "PXHD", description: "Protocol Exception Handling Disable", size: "1", shift: "12", mask: "0x1000" },
			{ name: "EFBI", description: "Edge Filtering During Bus Integration", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TXP", description: "Transmit Pause", size: "1", shift: "14", mask: "0x4000" },
			{ name: "NISO", description: "Non-ISO Operation", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "NBTP", description: "MCAN Nominal Bit Timing and Prescaler Register", offset: "0xE", size: "32",
		bits: [
			{ name: "NTSEG2", description: "Nominal Time Segment After Sample Point", size: "7", shift: "0", mask: "0x7F" },
			{ name: "NTSEG1", description: "Nominal Time Segment Before Sample Point", size: "8", shift: "8", mask: "0xFF00" },
			{ name: "NBRP", description: "Nominal Bit Rate Prescaler", size: "9", shift: "16", mask: "0x1FF0000" },
			{ name: "NSJW", description: "Nominal (Re)Synchronization Jump Width", size: "7", shift: "25", mask: "0xFE000000" },
		]
	},
	{ name: "TSCC", description: "MCAN Timestamp Counter Configuration", offset: "0x10", size: "32",
		bits: [
			{ name: "TSS", description: "Timestamp Select", size: "2", shift: "0", mask: "0x3" },
			{ name: "TCP", description: "Timestamp Counter Prescaler", size: "4", shift: "16", mask: "0xF0000" },
		]
	},
	{ name: "TSCV", description: "MCAN Timestamp Counter Value", offset: "0x12", size: "32",
		bits: [
			{ name: "TSC", description: "Timestamp Counter", size: "16", shift: "0", mask: "0xFFFF" },
		]
	},
	{ name: "TOCC", description: "MCAN Timeout Counter Configuration", offset: "0x14", size: "32",
		bits: [
			{ name: "ETOC", description: "Enable Timeout Counter", size: "1", shift: "0", mask: "0x1" },
			{ name: "TOS", description: "Timeout Select", size: "2", shift: "1", mask: "0x6" },
			{ name: "TOP", description: "Timeout Period", size: "16", shift: "16", mask: "0xFFFF0000" },
		]
	},
	{ name: "TOCV", description: "MCAN Timeout Counter Value", offset: "0x16", size: "32",
		bits: [
			{ name: "TOC", description: "Timeout Counter", size: "16", shift: "0", mask: "0xFFFF" },
		]
	},
	{ name: "ECR", description: "MCAN Error Counter Register", offset: "0x20", size: "32",
		bits: [
			{ name: "TEC", description: "Transmit Error Counter", size: "8", shift: "0", mask: "0xFF" },
			{ name: "REC", description: "Receive Error Counter", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "RP", description: "Receive Error Passive", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CEL", description: "CAN Error Logging", size: "8", shift: "16", mask: "0xFF0000" },
		]
	},
	{ name: "PSR", description: "MCAN Protocol Status Register", offset: "0x22", size: "32",
		bits: [
			{ name: "LEC", description: "Last Error Code", size: "3", shift: "0", mask: "0x7" },
			{ name: "ACT", description: "Node Activity", size: "2", shift: "3", mask: "0x18" },
			{ name: "EP", description: "Error Passive", size: "1", shift: "5", mask: "0x20" },
			{ name: "EW", description: "Warning Status", size: "1", shift: "6", mask: "0x40" },
			{ name: "BO", description: "Bus_Off Status", size: "1", shift: "7", mask: "0x80" },
			{ name: "DLEC", description: "Data Phase Last Error Code", size: "3", shift: "8", mask: "0x700" },
			{ name: "RESI", description: "ESI Flag of Last Received CAN FD Message", size: "1", shift: "11", mask: "0x800" },
			{ name: "RBRS", description: "BRS Flag of Last Received CAN FD Message", size: "1", shift: "12", mask: "0x1000" },
			{ name: "RFDF", description: "Received a CAN FD Message", size: "1", shift: "13", mask: "0x2000" },
			{ name: "PXE", description: "Protocol Exception Event", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TDCV", description: "Transmitter Delay Compensation Value", size: "7", shift: "16", mask: "0x7F0000" },
		]
	},
	{ name: "TDCR", description: "MCAN Transmitter Delay Compensation Register", offset: "0x24", size: "32",
		bits: [
			{ name: "TDCF", description: "Transmitter Delay Compensation Filter Window Length", size: "7", shift: "0", mask: "0x7F" },
			{ name: "TDCO", description: "Transmitter Delay Compensation Offset", size: "7", shift: "8", mask: "0x7F00" },
		]
	},
	{ name: "IR", description: "MCAN Interrupt Register", offset: "0x28", size: "32",
		bits: [
			{ name: "RF0N", description: "Rx FIFO 0 New Message", size: "1", shift: "0", mask: "0x1" },
			{ name: "RF0W", description: "Rx FIFO 0 Watermark Reached", size: "1", shift: "1", mask: "0x2" },
			{ name: "RF0F", description: "Rx FIFO 0 Full", size: "1", shift: "2", mask: "0x4" },
			{ name: "RF0L", description: "Rx FIFO 0 Message Lost", size: "1", shift: "3", mask: "0x8" },
			{ name: "RF1N", description: "Rx FIFO 1 New Message", size: "1", shift: "4", mask: "0x10" },
			{ name: "RF1W", description: "Rx FIFO 1 Watermark Reached", size: "1", shift: "5", mask: "0x20" },
			{ name: "RF1F", description: "Rx FIFO 1 Full", size: "1", shift: "6", mask: "0x40" },
			{ name: "RF1L", description: "Rx FIFO 1 Message Lost", size: "1", shift: "7", mask: "0x80" },
			{ name: "HPM", description: "High Priority Message", size: "1", shift: "8", mask: "0x100" },
			{ name: "TC", description: "Transmission Completed", size: "1", shift: "9", mask: "0x200" },
			{ name: "TCF", description: "Transmission Cancellation Finished", size: "1", shift: "10", mask: "0x400" },
			{ name: "TFE", description: "Tx FIFO Empty", size: "1", shift: "11", mask: "0x800" },
			{ name: "TEFN", description: "Tx Event FIFO New Entry", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TEFW", description: "Tx Event FIFO Watermark Reached", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TEFF", description: "Tx Event FIFO Full", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TEFL", description: "Tx Event FIFO Element Lost", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TSW", description: "Timestamp Wraparound", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MRAF", description: "Message RAM Access Failure", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TOO", description: "Timeout Occurred", size: "1", shift: "18", mask: "0x40000" },
			{ name: "DRX", description: "Message Stored to Dedicated Rx Buffer", size: "1", shift: "19", mask: "0x80000" },
			{ name: "BEU", description: "Bit Error Uncorrected", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ELO", description: "Error Logging Overflow", size: "1", shift: "22", mask: "0x400000" },
			{ name: "EP", description: "Error Passive", size: "1", shift: "23", mask: "0x800000" },
			{ name: "EW", description: "Warning Status", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "BO", description: "Bus_Off Status", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "WDI", description: "Watchdog Interrupt", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "PEA", description: "Protocol Error in Arbitration Phase", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "PED", description: "Protocol Error in Data Phase", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ARA", description: "Access to Reserved Address", size: "1", shift: "29", mask: "0x20000000" },
		]
	},
	{ name: "IE", description: "MCAN Interrupt Enable", offset: "0x2A", size: "32",
		bits: [
			{ name: "RF0NE", description: "Rx FIFO 0 New Message Enable", size: "1", shift: "0", mask: "0x1" },
			{ name: "RF0WE", description: "Rx FIFO 0 Watermark Reached Enable", size: "1", shift: "1", mask: "0x2" },
			{ name: "RF0FE", description: "Rx FIFO 0 Full Enable", size: "1", shift: "2", mask: "0x4" },
			{ name: "RF0LE", description: "Rx FIFO 0 Message Lost Enable", size: "1", shift: "3", mask: "0x8" },
			{ name: "RF1NE", description: "Rx FIFO 1 New Message Enable", size: "1", shift: "4", mask: "0x10" },
			{ name: "RF1WE", description: "Rx FIFO 1 Watermark Reached Enable", size: "1", shift: "5", mask: "0x20" },
			{ name: "RF1FE", description: "Rx FIFO 1 Full Enable", size: "1", shift: "6", mask: "0x40" },
			{ name: "RF1LE", description: "Rx FIFO 1 Message Lost Enable", size: "1", shift: "7", mask: "0x80" },
			{ name: "HPME", description: "High Priority Message Enable", size: "1", shift: "8", mask: "0x100" },
			{ name: "TCE", description: "Transmission Completed Enable", size: "1", shift: "9", mask: "0x200" },
			{ name: "TCFE", description: "Transmission Cancellation Finished Enable", size: "1", shift: "10", mask: "0x400" },
			{ name: "TFEE", description: "Tx FIFO Empty Enable", size: "1", shift: "11", mask: "0x800" },
			{ name: "TEFNE", description: "Tx Event FIFO New Entry Enable", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TEFWE", description: "Tx Event FIFO Watermark Reached Enable", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TEFFE", description: "Tx Event FIFO Full Enable", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TEFLE", description: "Tx Event FIFO Element Lost Enable", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TSWE", description: "Timestamp Wraparound Enable", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MRAFE", description: "Message RAM Access Failure Enable", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TOOE", description: "Timeout Occurred Enable", size: "1", shift: "18", mask: "0x40000" },
			{ name: "DRXE", description: "Message Stored to Dedicated Rx Buffer Enable", size: "1", shift: "19", mask: "0x80000" },
			{ name: "BECE", description: "Bit Error Corrected Enable", size: "1", shift: "20", mask: "0x100000" },
			{ name: "BEUE", description: "Bit Error Uncorrected Enable", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ELOE", description: "Error Logging Overflow Enable", size: "1", shift: "22", mask: "0x400000" },
			{ name: "EPE", description: "Error Passive Enable", size: "1", shift: "23", mask: "0x800000" },
			{ name: "EWE", description: "Warning Status Enable", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "BOE", description: "Bus_Off Status Enable", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "WDIE", description: "Watchdog Interrupt Enable", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "PEAE", description: "Protocol Error in Arbitration Phase Enable", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "PEDE", description: "Protocol Error in Data Phase Enable", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ARAE", description: "Access to Reserved Address Enable", size: "1", shift: "29", mask: "0x20000000" },
		]
	},
	{ name: "ILS", description: "MCAN Interrupt Line Select", offset: "0x2C", size: "32",
		bits: [
			{ name: "RF0NL", description: "Rx FIFO 0 New Message Line", size: "1", shift: "0", mask: "0x1" },
			{ name: "RF0WL", description: "Rx FIFO 0 Watermark Reached Line", size: "1", shift: "1", mask: "0x2" },
			{ name: "RF0FL", description: "Rx FIFO 0 Full Line", size: "1", shift: "2", mask: "0x4" },
			{ name: "RF0LL", description: "Rx FIFO 0 Message Lost Line", size: "1", shift: "3", mask: "0x8" },
			{ name: "RF1NL", description: "Rx FIFO 1 New Message Line", size: "1", shift: "4", mask: "0x10" },
			{ name: "RF1WL", description: "Rx FIFO 1 Watermark Reached Line", size: "1", shift: "5", mask: "0x20" },
			{ name: "RF1FL", description: "Rx FIFO 1 Full Line", size: "1", shift: "6", mask: "0x40" },
			{ name: "RF1LL", description: "Rx FIFO 1 Message Lost Line", size: "1", shift: "7", mask: "0x80" },
			{ name: "HPML", description: "High Priority Message Line", size: "1", shift: "8", mask: "0x100" },
			{ name: "TCL", description: "Transmission Completed Line", size: "1", shift: "9", mask: "0x200" },
			{ name: "TCFL", description: "Transmission Cancellation Finished Line", size: "1", shift: "10", mask: "0x400" },
			{ name: "TFEL", description: "Tx FIFO Empty Line", size: "1", shift: "11", mask: "0x800" },
			{ name: "TEFNL", description: "Tx Event FIFO New Entry Line", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TEFWL", description: "Tx Event FIFO Watermark Reached Line", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TEFFL", description: "Tx Event FIFO Full Line", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TEFLL", description: "Tx Event FIFO Element Lost Line", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TSWL", description: "Timestamp Wraparound Line", size: "1", shift: "16", mask: "0x10000" },
			{ name: "MRAFL", description: "Message RAM Access Failure Line", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TOOL", description: "Timeout Occurred Line", size: "1", shift: "18", mask: "0x40000" },
			{ name: "DRXL", description: "Message Stored to Dedicated Rx Buffer Line", size: "1", shift: "19", mask: "0x80000" },
			{ name: "BECL", description: "Bit Error Corrected Line", size: "1", shift: "20", mask: "0x100000" },
			{ name: "BEUL", description: "Bit Error Uncorrected Line", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ELOL", description: "Error Logging Overflow Line", size: "1", shift: "22", mask: "0x400000" },
			{ name: "EPL", description: "Error Passive Line", size: "1", shift: "23", mask: "0x800000" },
			{ name: "EWL", description: "Warning Status Line", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "BOL", description: "Bus_Off Status Line", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "WDIL", description: "Watchdog Interrupt Line", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "PEAL", description: "Protocol Error in Arbitration Phase Line", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "PEDL", description: "Protocol Error in Data Phase Line", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ARAL", description: "Access to Reserved Address Line", size: "1", shift: "29", mask: "0x20000000" },
		]
	},
	{ name: "ILE", description: "MCAN Interrupt Line Enable", offset: "0x2E", size: "32",
		bits: [
			{ name: "EINT0", description: "Enable Interrupt Line 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "EINT1", description: "Enable Interrupt Line 1", size: "1", shift: "1", mask: "0x2" },
		]
	},
	{ name: "GFC", description: "MCAN Global Filter Configuration", offset: "0x40", size: "32",
		bits: [
			{ name: "RRFE", description: "Reject Remote Frames Extended", size: "1", shift: "0", mask: "0x1" },
			{ name: "RRFS", description: "Reject Remote Frames Standard", size: "1", shift: "1", mask: "0x2" },
			{ name: "ANFE", description: "Accept Non-matching Frames Extended", size: "2", shift: "2", mask: "0xC" },
			{ name: "ANFS", description: "Accept Non-matching Frames Standard", size: "2", shift: "4", mask: "0x30" },
		]
	},
	{ name: "SIDFC", description: "MCAN Standard ID Filter Configuration", offset: "0x42", size: "32",
		bits: [
			{ name: "FLSSA", description: "Filter List Standard Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "LSS", description: "List Size Standard", size: "8", shift: "16", mask: "0xFF0000" },
		]
	},
	{ name: "XIDFC", description: "MCAN Extended ID Filter Configuration", offset: "0x44", size: "32",
		bits: [
			{ name: "FLESA", description: "Filter List Extended Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "LSE", description: "List Size Extended", size: "7", shift: "16", mask: "0x7F0000" },
		]
	},
	{ name: "XIDAM", description: "MCAN Extended ID and Mask", offset: "0x48", size: "32",
		bits: [
			{ name: "EIDM", description: "Extended ID Mask", size: "29", shift: "0", mask: "0x1FFFFFFF" },
		]
	},
	{ name: "HPMS", description: "MCAN High Priority Message Status", offset: "0x4A", size: "32",
		bits: [
			{ name: "BIDX", description: "Buffer Index", size: "6", shift: "0", mask: "0x3F" },
			{ name: "MSI", description: "Message Storage Indicator", size: "2", shift: "6", mask: "0xC0" },
			{ name: "FIDX", description: "Filter Index", size: "7", shift: "8", mask: "0x7F00" },
			{ name: "FLST", description: "Filter List", size: "1", shift: "15", mask: "0x8000" },
		]
	},
	{ name: "NDAT1", description: "MCAN New Data 1", offset: "0x4C", size: "32",
		bits: [
			{ name: "ND0", description: "New Data RX Buffer 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "ND1", description: "New Data RX Buffer 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "ND2", description: "New Data RX Buffer 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "ND3", description: "New Data RX Buffer 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "ND4", description: "New Data RX Buffer 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "ND5", description: "New Data RX Buffer 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "ND6", description: "New Data RX Buffer 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "ND7", description: "New Data RX Buffer 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "ND8", description: "New Data RX Buffer 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "ND9", description: "New Data RX Buffer 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "ND10", description: "New Data RX Buffer 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "ND11", description: "New Data RX Buffer 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "ND12", description: "New Data RX Buffer 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ND13", description: "New Data RX Buffer 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ND14", description: "New Data RX Buffer 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ND15", description: "New Data RX Buffer 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ND16", description: "New Data RX Buffer 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ND17", description: "New Data RX Buffer 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ND18", description: "New Data RX Buffer 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ND19", description: "New Data RX Buffer 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ND20", description: "New Data RX Buffer 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ND21", description: "New Data RX Buffer 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ND22", description: "New Data RX Buffer 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ND23", description: "New Data RX Buffer 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ND24", description: "New Data RX Buffer 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ND25", description: "New Data RX Buffer 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ND26", description: "New Data RX Buffer 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ND27", description: "New Data RX Buffer 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ND28", description: "New Data RX Buffer 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ND29", description: "New Data RX Buffer 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ND30", description: "New Data RX Buffer 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ND31", description: "New Data RX Buffer 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "NDAT2", description: "MCAN New Data 2", offset: "0x4E", size: "32",
		bits: [
			{ name: "ND32", description: "New Data RX Buffer 32", size: "1", shift: "0", mask: "0x1" },
			{ name: "ND33", description: "New Data RX Buffer 33", size: "1", shift: "1", mask: "0x2" },
			{ name: "ND34", description: "New Data RX Buffer 34", size: "1", shift: "2", mask: "0x4" },
			{ name: "ND35", description: "New Data RX Buffer 35", size: "1", shift: "3", mask: "0x8" },
			{ name: "ND36", description: "New Data RX Buffer 36", size: "1", shift: "4", mask: "0x10" },
			{ name: "ND37", description: "New Data RX Buffer 37", size: "1", shift: "5", mask: "0x20" },
			{ name: "ND38", description: "New Data RX Buffer 38", size: "1", shift: "6", mask: "0x40" },
			{ name: "ND39", description: "New Data RX Buffer 39", size: "1", shift: "7", mask: "0x80" },
			{ name: "ND40", description: "New Data RX Buffer 40", size: "1", shift: "8", mask: "0x100" },
			{ name: "ND41", description: "New Data RX Buffer 41", size: "1", shift: "9", mask: "0x200" },
			{ name: "ND42", description: "New Data RX Buffer 42", size: "1", shift: "10", mask: "0x400" },
			{ name: "ND43", description: "New Data RX Buffer 43", size: "1", shift: "11", mask: "0x800" },
			{ name: "ND44", description: "New Data RX Buffer 44", size: "1", shift: "12", mask: "0x1000" },
			{ name: "ND45", description: "New Data RX Buffer 45", size: "1", shift: "13", mask: "0x2000" },
			{ name: "ND46", description: "New Data RX Buffer 46", size: "1", shift: "14", mask: "0x4000" },
			{ name: "ND47", description: "New Data RX Buffer 47", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ND48", description: "New Data RX Buffer 48", size: "1", shift: "16", mask: "0x10000" },
			{ name: "ND49", description: "New Data RX Buffer 49", size: "1", shift: "17", mask: "0x20000" },
			{ name: "ND50", description: "New Data RX Buffer 50", size: "1", shift: "18", mask: "0x40000" },
			{ name: "ND51", description: "New Data RX Buffer 51", size: "1", shift: "19", mask: "0x80000" },
			{ name: "ND52", description: "New Data RX Buffer 52", size: "1", shift: "20", mask: "0x100000" },
			{ name: "ND53", description: "New Data RX Buffer 53", size: "1", shift: "21", mask: "0x200000" },
			{ name: "ND54", description: "New Data RX Buffer 54", size: "1", shift: "22", mask: "0x400000" },
			{ name: "ND55", description: "New Data RX Buffer 55", size: "1", shift: "23", mask: "0x800000" },
			{ name: "ND56", description: "New Data RX Buffer 56", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "ND57", description: "New Data RX Buffer 57", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "ND58", description: "New Data RX Buffer 58", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "ND59", description: "New Data RX Buffer 59", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "ND60", description: "New Data RX Buffer 60", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "ND61", description: "New Data RX Buffer 61", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "ND62", description: "New Data RX Buffer 62", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "ND63", description: "New Data RX Buffer 63", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "RXF0C", description: "MCAN Rx FIFO 0 Configuration", offset: "0x50", size: "32",
		bits: [
			{ name: "F0SA", description: "Rx FIFO 0 Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "F0S", description: "Rx FIFO 0 Size", size: "7", shift: "16", mask: "0x7F0000" },
			{ name: "F0WM", description: "Rx FIFO 0 Watermark", size: "7", shift: "24", mask: "0x7F000000" },
			{ name: "F0OM", description: "FIFO 0 Operation Mode", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "RXF0S", description: "MCAN Rx FIFO 0 Status", offset: "0x52", size: "32",
		bits: [
			{ name: "F0FL", description: "Rx FIFO 0 Fill Level", size: "7", shift: "0", mask: "0x7F" },
			{ name: "F0GI", description: "Rx FIFO 0 Get Index", size: "6", shift: "8", mask: "0x3F00" },
			{ name: "F0PI", description: "Rx FIFO 0 Put Index", size: "6", shift: "16", mask: "0x3F0000" },
			{ name: "F0F", description: "Rx FIFO 0 Full", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "RF0L", description: "Rx FIFO 0 Message Lost", size: "1", shift: "25", mask: "0x2000000" },
		]
	},
	{ name: "RXF0A", description: "MCAN Rx FIFO 0 Acknowledge", offset: "0x54", size: "32",
		bits: [
			{ name: "F0AI", description: "Rx FIFO 0 Acknowledge Index", size: "6", shift: "0", mask: "0x3F" },
		]
	},
	{ name: "RXBC", description: "MCAN Rx Buffer Configuration", offset: "0x56", size: "32",
		bits: [
			{ name: "RBSA", description: "Rx Buffer Start Address", size: "14", shift: "2", mask: "0xFFFC" },
		]
	},
	{ name: "RXF1C", description: "MCAN Rx FIFO 1 Configuration", offset: "0x58", size: "32",
		bits: [
			{ name: "F1SA", description: "Rx FIFO 1 Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "F1S", description: "Rx FIFO 1 Size", size: "7", shift: "16", mask: "0x7F0000" },
			{ name: "F1WM", description: "Rx FIFO 1 Watermark", size: "7", shift: "24", mask: "0x7F000000" },
			{ name: "F1OM", description: "FIFO 1 Operation Mode", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "RXF1S", description: "MCAN Rx FIFO 1 Status", offset: "0x5A", size: "32",
		bits: [
			{ name: "F1FL", description: "Rx FIFO 1 Fill Level", size: "7", shift: "0", mask: "0x7F" },
			{ name: "F1GI", description: "Rx FIFO 1 Get Index", size: "6", shift: "8", mask: "0x3F00" },
			{ name: "F1PI", description: "Rx FIFO 1 Put Index", size: "6", shift: "16", mask: "0x3F0000" },
			{ name: "F1F", description: "Rx FIFO 1 Full", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "RF1L", description: "Rx FIFO 1 Message Lost", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "DMS", description: "Debug Message Status", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "RXF1A", description: "MCAN Rx FIFO 1 Acknowledge", offset: "0x5C", size: "32",
		bits: [
			{ name: "F1AI", description: "Rx FIFO 1 Acknowledge Index", size: "6", shift: "0", mask: "0x3F" },
		]
	},
	{ name: "RXESC", description: "MCAN Rx Buffer / FIFO Element Size Configuration", offset: "0x5E", size: "32",
		bits: [
			{ name: "F0DS", description: "Rx FIFO 0 Data Field Size", size: "3", shift: "0", mask: "0x7" },
			{ name: "F1DS", description: "Rx FIFO 1 Data Field Size", size: "3", shift: "4", mask: "0x70" },
			{ name: "RBDS", description: "Rx Buffer Data Field Size", size: "3", shift: "8", mask: "0x700" },
		]
	},
	{ name: "TXBC", description: "MCAN Tx Buffer Configuration", offset: "0x60", size: "32",
		bits: [
			{ name: "TBSA", description: "Tx Buffers Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "NDTB", description: "Number of Dedicated Transmit Buffers", size: "6", shift: "16", mask: "0x3F0000" },
			{ name: "TFQS", description: "Transmit FIFO/Queue Size", size: "6", shift: "24", mask: "0x3F000000" },
			{ name: "TFQM", description: "Tx FIFO/Queue Mode", size: "1", shift: "30", mask: "0x40000000" },
		]
	},
	{ name: "TXFQS", description: "MCAN Tx FIFO / Queue Status", offset: "0x62", size: "32",
		bits: [
			{ name: "TFFL", description: "Tx FIFO Free Level", size: "6", shift: "0", mask: "0x3F" },
			{ name: "TFGI", description: "Tx FIFO Get Index", size: "5", shift: "8", mask: "0x1F00" },
			{ name: "TFQP", description: "Tx FIFO/Queue Put Index", size: "5", shift: "16", mask: "0x1F0000" },
			{ name: "TFQF", description: "Tx FIFO/Queue Full", size: "1", shift: "21", mask: "0x200000" },
		]
	},
	{ name: "TXESC", description: "MCAN Tx Buffer Element Size Configuration", offset: "0x64", size: "32",
		bits: [
			{ name: "TBDS", description: "Tx Buffer Data Field Size", size: "3", shift: "0", mask: "0x7" },
		]
	},
	{ name: "TXBRP", description: "MCAN Tx Buffer Request Pending", offset: "0x66", size: "32",
		bits: [
			{ name: "TRP0", description: "Transmission Request Pending 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "TRP1", description: "Transmission Request Pending 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "TRP2", description: "Transmission Request Pending 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "TRP3", description: "Transmission Request Pending 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "TRP4", description: "Transmission Request Pending 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "TRP5", description: "Transmission Request Pending 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "TRP6", description: "Transmission Request Pending 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "TRP7", description: "Transmission Request Pending 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "TRP8", description: "Transmission Request Pending 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "TRP9", description: "Transmission Request Pending 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "TRP10", description: "Transmission Request Pending 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "TRP11", description: "Transmission Request Pending 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "TRP12", description: "Transmission Request Pending 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TRP13", description: "Transmission Request Pending 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TRP14", description: "Transmission Request Pending 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TRP15", description: "Transmission Request Pending 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TRP16", description: "Transmission Request Pending 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "TRP17", description: "Transmission Request Pending 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TRP18", description: "Transmission Request Pending 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "TRP19", description: "Transmission Request Pending 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "TRP20", description: "Transmission Request Pending 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "TRP21", description: "Transmission Request Pending 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "TRP22", description: "Transmission Request Pending 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "TRP23", description: "Transmission Request Pending 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "TRP24", description: "Transmission Request Pending 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "TRP25", description: "Transmission Request Pending 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "TRP26", description: "Transmission Request Pending 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "TRP27", description: "Transmission Request Pending 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "TRP28", description: "Transmission Request Pending 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "TRP29", description: "Transmission Request Pending 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "TRP30", description: "Transmission Request Pending 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "TRP31", description: "Transmission Request Pending 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBAR", description: "MCAN Tx Buffer Add Request", offset: "0x68", size: "32",
		bits: [
			{ name: "AR0", description: "Add Request 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "AR1", description: "Add Request 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "AR2", description: "Add Request 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "AR3", description: "Add Request 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "AR4", description: "Add Request 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "AR5", description: "Add Request 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "AR6", description: "Add Request 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "AR7", description: "Add Request 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "AR8", description: "Add Request 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "AR9", description: "Add Request 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "AR10", description: "Add Request 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "AR11", description: "Add Request 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "AR12", description: "Add Request 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "AR13", description: "Add Request 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "AR14", description: "Add Request 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "AR15", description: "Add Request 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "AR16", description: "Add Request 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "AR17", description: "Add Request 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "AR18", description: "Add Request 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "AR19", description: "Add Request 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "AR20", description: "Add Request 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "AR21", description: "Add Request 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "AR22", description: "Add Request 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "AR23", description: "Add Request 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "AR24", description: "Add Request 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "AR25", description: "Add Request 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "AR26", description: "Add Request 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "AR27", description: "Add Request 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "AR28", description: "Add Request 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "AR29", description: "Add Request 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "AR30", description: "Add Request 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "AR31", description: "Add Request 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBCR", description: "MCAN Tx Buffer Cancellation Request", offset: "0x6A", size: "32",
		bits: [
			{ name: "CR0", description: "Cancellation Request 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "CR1", description: "Cancellation Request 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "CR2", description: "Cancellation Request 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "CR3", description: "Cancellation Request 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "CR4", description: "Cancellation Request 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "CR5", description: "Cancellation Request 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "CR6", description: "Cancellation Request 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "CR7", description: "Cancellation Request 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "CR8", description: "Cancellation Request 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "CR9", description: "Cancellation Request 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "CR10", description: "Cancellation Request 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "CR11", description: "Cancellation Request 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "CR12", description: "Cancellation Request 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CR13", description: "Cancellation Request 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CR14", description: "Cancellation Request 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CR15", description: "Cancellation Request 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CR16", description: "Cancellation Request 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CR17", description: "Cancellation Request 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CR18", description: "Cancellation Request 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CR19", description: "Cancellation Request 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CR20", description: "Cancellation Request 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CR21", description: "Cancellation Request 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CR22", description: "Cancellation Request 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CR23", description: "Cancellation Request 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CR24", description: "Cancellation Request 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CR25", description: "Cancellation Request 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CR26", description: "Cancellation Request 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CR27", description: "Cancellation Request 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CR28", description: "Cancellation Request 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CR29", description: "Cancellation Request 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CR30", description: "Cancellation Request 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CR31", description: "Cancellation Request 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBTO", description: "MCAN Tx Buffer Transmission Occurred", offset: "0x6C", size: "32",
		bits: [
			{ name: "TO0", description: "Transmission Occurred 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "TO1", description: "Transmission Occurred 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "TO2", description: "Transmission Occurred 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "TO3", description: "Transmission Occurred 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "TO4", description: "Transmission Occurred 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "TO5", description: "Transmission Occurred 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "TO6", description: "Transmission Occurred 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "TO7", description: "Transmission Occurred 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "TO8", description: "Transmission Occurred 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "TO9", description: "Transmission Occurred 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "TO10", description: "Transmission Occurred 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "TO11", description: "Transmission Occurred 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "TO12", description: "Transmission Occurred 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TO13", description: "Transmission Occurred 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TO14", description: "Transmission Occurred 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TO15", description: "Transmission Occurred 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TO16", description: "Transmission Occurred 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "TO17", description: "Transmission Occurred 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TO18", description: "Transmission Occurred 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "TO19", description: "Transmission Occurred 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "TO20", description: "Transmission Occurred 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "TO21", description: "Transmission Occurred 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "TO22", description: "Transmission Occurred 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "TO23", description: "Transmission Occurred 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "TO24", description: "Transmission Occurred 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "TO25", description: "Transmission Occurred 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "TO26", description: "Transmission Occurred 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "TO27", description: "Transmission Occurred 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "TO28", description: "Transmission Occurred 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "TO29", description: "Transmission Occurred 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "TO30", description: "Transmission Occurred 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "TO31", description: "Transmission Occurred 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBCF", description: "MCAN Tx Buffer Cancellation Finished", offset: "0x6E", size: "32",
		bits: [
			{ name: "CF0", description: "Cancellation Finished 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "CF1", description: "Cancellation Finished 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "CF2", description: "Cancellation Finished 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "CF3", description: "Cancellation Finished 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "CF4", description: "Cancellation Finished 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "CF5", description: "Cancellation Finished 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "CF6", description: "Cancellation Finished 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "CF7", description: "Cancellation Finished 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "CF8", description: "Cancellation Finished 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "CF9", description: "Cancellation Finished 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "CF10", description: "Cancellation Finished 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "CF11", description: "Cancellation Finished 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "CF12", description: "Cancellation Finished 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CF13", description: "Cancellation Finished 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CF14", description: "Cancellation Finished 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CF15", description: "Cancellation Finished 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CF16", description: "Cancellation Finished 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CF17", description: "Cancellation Finished 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CF18", description: "Cancellation Finished 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CF19", description: "Cancellation Finished 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CF20", description: "Cancellation Finished 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CF21", description: "Cancellation Finished 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CF22", description: "Cancellation Finished 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CF23", description: "Cancellation Finished 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CF24", description: "Cancellation Finished 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CF25", description: "Cancellation Finished 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CF26", description: "Cancellation Finished 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CF27", description: "Cancellation Finished 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CF28", description: "Cancellation Finished 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CF29", description: "Cancellation Finished 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CF30", description: "Cancellation Finished 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CF31", description: "Cancellation Finished 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBTIE", description: "MCAN Tx Buffer Transmission Interrupt Enable", offset: "0x70", size: "32",
		bits: [
			{ name: "TIE0", description: "Transmission Interrupt Enable 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "TIE1", description: "Transmission Interrupt Enable 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "TIE2", description: "Transmission Interrupt Enable 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "TIE3", description: "Transmission Interrupt Enable 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "TIE4", description: "Transmission Interrupt Enable 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "TIE5", description: "Transmission Interrupt Enable 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "TIE6", description: "Transmission Interrupt Enable 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "TIE7", description: "Transmission Interrupt Enable 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "TIE8", description: "Transmission Interrupt Enable 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "TIE9", description: "Transmission Interrupt Enable 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "TIE10", description: "Transmission Interrupt Enable 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "TIE11", description: "Transmission Interrupt Enable 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "TIE12", description: "Transmission Interrupt Enable 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "TIE13", description: "Transmission Interrupt Enable 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "TIE14", description: "Transmission Interrupt Enable 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "TIE15", description: "Transmission Interrupt Enable 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "TIE16", description: "Transmission Interrupt Enable 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "TIE17", description: "Transmission Interrupt Enable 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "TIE18", description: "Transmission Interrupt Enable 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "TIE19", description: "Transmission Interrupt Enable 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "TIE20", description: "Transmission Interrupt Enable 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "TIE21", description: "Transmission Interrupt Enable 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "TIE22", description: "Transmission Interrupt Enable 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "TIE23", description: "Transmission Interrupt Enable 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "TIE24", description: "Transmission Interrupt Enable 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "TIE25", description: "Transmission Interrupt Enable 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "TIE26", description: "Transmission Interrupt Enable 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "TIE27", description: "Transmission Interrupt Enable 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "TIE28", description: "Transmission Interrupt Enable 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "TIE29", description: "Transmission Interrupt Enable 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "TIE30", description: "Transmission Interrupt Enable 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "TIE31", description: "Transmission Interrupt Enable 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXBCIE", description: "MCAN Tx Buffer Cancellation Finished Interrupt Enable", offset: "0x72", size: "32",
		bits: [
			{ name: "CFIE0", description: "Cancellation Finished Interrupt Enable 0", size: "1", shift: "0", mask: "0x1" },
			{ name: "CFIE1", description: "Cancellation Finished Interrupt Enable 1", size: "1", shift: "1", mask: "0x2" },
			{ name: "CFIE2", description: "Cancellation Finished Interrupt Enable 2", size: "1", shift: "2", mask: "0x4" },
			{ name: "CFIE3", description: "Cancellation Finished Interrupt Enable 3", size: "1", shift: "3", mask: "0x8" },
			{ name: "CFIE4", description: "Cancellation Finished Interrupt Enable 4", size: "1", shift: "4", mask: "0x10" },
			{ name: "CFIE5", description: "Cancellation Finished Interrupt Enable 5", size: "1", shift: "5", mask: "0x20" },
			{ name: "CFIE6", description: "Cancellation Finished Interrupt Enable 6", size: "1", shift: "6", mask: "0x40" },
			{ name: "CFIE7", description: "Cancellation Finished Interrupt Enable 7", size: "1", shift: "7", mask: "0x80" },
			{ name: "CFIE8", description: "Cancellation Finished Interrupt Enable 8", size: "1", shift: "8", mask: "0x100" },
			{ name: "CFIE9", description: "Cancellation Finished Interrupt Enable 9", size: "1", shift: "9", mask: "0x200" },
			{ name: "CFIE10", description: "Cancellation Finished Interrupt Enable 10", size: "1", shift: "10", mask: "0x400" },
			{ name: "CFIE11", description: "Cancellation Finished Interrupt Enable 11", size: "1", shift: "11", mask: "0x800" },
			{ name: "CFIE12", description: "Cancellation Finished Interrupt Enable 12", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CFIE13", description: "Cancellation Finished Interrupt Enable 13", size: "1", shift: "13", mask: "0x2000" },
			{ name: "CFIE14", description: "Cancellation Finished Interrupt Enable 14", size: "1", shift: "14", mask: "0x4000" },
			{ name: "CFIE15", description: "Cancellation Finished Interrupt Enable 15", size: "1", shift: "15", mask: "0x8000" },
			{ name: "CFIE16", description: "Cancellation Finished Interrupt Enable 16", size: "1", shift: "16", mask: "0x10000" },
			{ name: "CFIE17", description: "Cancellation Finished Interrupt Enable 17", size: "1", shift: "17", mask: "0x20000" },
			{ name: "CFIE18", description: "Cancellation Finished Interrupt Enable 18", size: "1", shift: "18", mask: "0x40000" },
			{ name: "CFIE19", description: "Cancellation Finished Interrupt Enable 19", size: "1", shift: "19", mask: "0x80000" },
			{ name: "CFIE20", description: "Cancellation Finished Interrupt Enable 20", size: "1", shift: "20", mask: "0x100000" },
			{ name: "CFIE21", description: "Cancellation Finished Interrupt Enable 21", size: "1", shift: "21", mask: "0x200000" },
			{ name: "CFIE22", description: "Cancellation Finished Interrupt Enable 22", size: "1", shift: "22", mask: "0x400000" },
			{ name: "CFIE23", description: "Cancellation Finished Interrupt Enable 23", size: "1", shift: "23", mask: "0x800000" },
			{ name: "CFIE24", description: "Cancellation Finished Interrupt Enable 24", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "CFIE25", description: "Cancellation Finished Interrupt Enable 25", size: "1", shift: "25", mask: "0x2000000" },
			{ name: "CFIE26", description: "Cancellation Finished Interrupt Enable 26", size: "1", shift: "26", mask: "0x4000000" },
			{ name: "CFIE27", description: "Cancellation Finished Interrupt Enable 27", size: "1", shift: "27", mask: "0x8000000" },
			{ name: "CFIE28", description: "Cancellation Finished Interrupt Enable 28", size: "1", shift: "28", mask: "0x10000000" },
			{ name: "CFIE29", description: "Cancellation Finished Interrupt Enable 29", size: "1", shift: "29", mask: "0x20000000" },
			{ name: "CFIE30", description: "Cancellation Finished Interrupt Enable 30", size: "1", shift: "30", mask: "0x40000000" },
			{ name: "CFIE31", description: "Cancellation Finished Interrupt Enable 31", size: "1", shift: "31", mask: "0x80000000" },
		]
	},
	{ name: "TXEFC", description: "MCAN Tx Event FIFO Configuration", offset: "0x78", size: "32",
		bits: [
			{ name: "EFSA", description: "Event FIFO Start Address", size: "14", shift: "2", mask: "0xFFFC" },
			{ name: "EFS", description: "Event FIFO Size", size: "6", shift: "16", mask: "0x3F0000" },
			{ name: "EFWM", description: "Event FIFO Watermark", size: "6", shift: "24", mask: "0x3F000000" },
		]
	},
	{ name: "TXEFS", description: "MCAN Tx Event FIFO Status", offset: "0x7A", size: "32",
		bits: [
			{ name: "EFFL", description: "Event FIFO Fill Level", size: "6", shift: "0", mask: "0x3F" },
			{ name: "EFGI", description: "Event FIFO Get Index", size: "5", shift: "8", mask: "0x1F00" },
			{ name: "EFPI", description: "Event FIFO Put Index", size: "5", shift: "16", mask: "0x1F0000" },
			{ name: "EFF", description: "Event FIFO Full", size: "1", shift: "24", mask: "0x1000000" },
			{ name: "TEFL", description: "Tx Event FIFO Element Lost", size: "1", shift: "25", mask: "0x2000000" },
		]
	},
	{ name: "TXEFA", description: "MCAN Tx Event FIFO Acknowledge", offset: "0x7C", size: "32",
		bits: [
			{ name: "EFAI", description: "Event FIFO Acknowledge Index", size: "5", shift: "0", mask: "0x1F" },
		]
	},
	{ name: "ERR_REV", description: "MCAN Error Aggregator Revision Register", offset: "0x0", size: "32",
		bits: [
			{ name: "REVMIN", description: "Minor Revision", size: "6", shift: "0", mask: "0x3F" },
			{ name: "REVMAJ", description: "Major Revision", size: "3", shift: "8", mask: "0x700" },
			{ name: "MODULE_ID", description: "Module Identification Number", size: "12", shift: "16", mask: "0xFFF0000" },
			{ name: "SCHEME", description: "PID Register Scheme", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "ERR_VECTOR", description: "MCAN ECC Vector Register", offset: "0x4", size: "32",
		bits: [
			{ name: "ECC_VECTOR", description: "ECC RAM ID", size: "11", shift: "0", mask: "0x7FF" },
			{ name: "RD_SVBUS", description: "Read Trigger", size: "1", shift: "15", mask: "0x8000" },
			{ name: "RD_SVBUS_ADDRESS", description: "Read Address Offset", size: "8", shift: "16", mask: "0xFF0000" },
			{ name: "RD_SVBUS_DONE", description: "Read Completion Flag", size: "1", shift: "24", mask: "0x1000000" },
		]
	},
	{ name: "ERR_STAT", description: "MCAN Error Misc Status", offset: "0x6", size: "16",
		bits: [
			{ name: "NUM_RAMS", description: "Number of RAMs", size: "11", shift: "0", mask: "0x7FF" },
		]
	},
	{ name: "ERR_WRAP_REV", description: "MCAN ECC Wrapper Revision Register", offset: "0x8", size: "32",
		bits: [
			{ name: "REVMIN", description: "Minor Revision", size: "6", shift: "0", mask: "0x3F" },
			{ name: "REVMAJ", description: "Major Revision", size: "3", shift: "8", mask: "0x700" },
			{ name: "MODULE_ID", description: "Module Identification Number", size: "12", shift: "16", mask: "0xFFF0000" },
			{ name: "SCHEME", description: "PID Register Scheme", size: "2", shift: "30", mask: "0xC0000000" },
		]
	},
	{ name: "ERR_CTRL", description: "MCAN ECC Control", offset: "0xA", size: "16",
		bits: [
			{ name: "ECC_ENABLE", description: "Enable ECC Generation", size: "1", shift: "0", mask: "0x1" },
			{ name: "ECC_CHECK", description: "Enable ECC Check", size: "1", shift: "1", mask: "0x2" },
			{ name: "ENABLE_RMW", description: "Enable Read-Modify-Write", size: "1", shift: "2", mask: "0x4" },
			{ name: "FORCE_SEC", description: "Force Single Bit Error Corrected Error", size: "1", shift: "3", mask: "0x8" },
			{ name: "FORCE_DED", description: "Force Double Bit Error Detected Error", size: "1", shift: "4", mask: "0x10" },
			{ name: "FORCE_N_ROW", description: "Force Next Single/Double Bit Error", size: "1", shift: "5", mask: "0x20" },
			{ name: "ERROR_ONCE", description: "Force Error Only Once Enable", size: "1", shift: "6", mask: "0x40" },
			{ name: "CHECK_SVBUS_TIMEOUT", description: "SVBUS Timeout Enable", size: "1", shift: "8", mask: "0x100" },
		]
	},
	{ name: "ERR_ERR_CTRL1", description: "MCAN ECC Error Control 1 Register", offset: "0xC", size: "16",
		bits: [
		]
	},
	{ name: "ERR_ERR_CTRL2", description: "MCAN ECC Error Control 2 Register", offset: "0xE", size: "32",
		bits: [
			{ name: "ECC_BIT1", description: "Force Error Bit1 Column Index", size: "16", shift: "0", mask: "0xFFFF" },
			{ name: "ECC_BIT2", description: "Force Error Bit2 Column Index", size: "16", shift: "16", mask: "0xFFFF0000" },
		]
	},
	{ name: "ERR_ERR_STAT1", description: "MCAN ECC Error Status 1 Register", offset: "0x10", size: "32",
		bits: [
			{ name: "ECC_SEC", description: "Single Bit Error Corrected Status", size: "2", shift: "0", mask: "0x3" },
			{ name: "ECC_DED", description: "Double Bit Error Detected Status", size: "2", shift: "2", mask: "0xC" },
			{ name: "ECC_OTHER", description: "SEC While Writeback Error Status", size: "1", shift: "4", mask: "0x10" },
			{ name: "CTRL_REG_ERROR", description: "Control Register Error", size: "1", shift: "7", mask: "0x80" },
			{ name: "CLR_ECC_SEC", description: "Clear ECC_SEC", size: "2", shift: "8", mask: "0x300" },
			{ name: "CLR_ECC_DED", description: "Clear ECC_DED", size: "2", shift: "10", mask: "0xC00" },
			{ name: "CLR_ECC_OTHER", description: "Clear ECC_OTHER", size: "1", shift: "12", mask: "0x1000" },
			{ name: "CLR_CTRL_REG_ERROR", description: "Clear Control Register Error", size: "1", shift: "15", mask: "0x8000" },
			{ name: "ECC_BIT1", description: "ECC Error Bit Position", size: "16", shift: "16", mask: "0xFFFF0000" },
		]
	},
	{ name: "ERR_ERR_STAT2", description: "MCAN ECC Error Status 2 Register", offset: "0x12", size: "16",
		bits: [
		]
	},
	{ name: "ERR_ERR_STAT3", description: "MCAN ECC Error Status 3 Register", offset: "0x14", size: "16",
		bits: [
			{ name: "WB_PEND", description: "Delayed Write Back Pending Status", size: "1", shift: "0", mask: "0x1" },
			{ name: "SVBUS_TIMEOUT", description: "Serial VBUS Timeout Flag", size: "1", shift: "1", mask: "0x2" },
			{ name: "CLR_SVBUS_TIMEOUT", description: "Clear Serial VBUS Timeout", size: "1", shift: "9", mask: "0x200" },
		]
	},
	{ name: "ERR_SEC_EOI", description: "MCAN Single Error Corrected End of Interrupt Register", offset: "0x1E", size: "16",
		bits: [
			{ name: "EOI_WR", description: "End of Interrupt", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_SEC_STATUS", description: "MCAN Single Error Corrected Interrupt Status Register", offset: "0x20", size: "16",
		bits: [
			{ name: "MSGMEM_PEND", description: "Message RAM SEC Interrupt Pending", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_SEC_ENABLE_SET", description: "MCAN Single Error Corrected Interrupt Enable Set Register", offset: "0x40", size: "16",
		bits: [
			{ name: "MSGMEM_ENABLE_SET", description: "Message RAM SEC Interrupt Pending Enable Set", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_SEC_ENABLE_CLR", description: "MCAN Single Error Corrected Interrupt Enable Clear Register", offset: "0x60", size: "16",
		bits: [
			{ name: "MSGMEM_ENABLE_CLR", description: "Message RAM SEC Interrupt Pending Enable Clear", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_DED_EOI", description: "MCAN Double Error Detected End of Interrupt Register", offset: "0x9E", size: "16",
		bits: [
			{ name: "EOI_WR", description: "End of Interrupt", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_DED_STATUS", description: "MCAN Double Error Detected Interrupt Status Register", offset: "0xA0", size: "16",
		bits: [
			{ name: "MSGMEM_PEND", description: "Message RAM DED Interrupt Pending", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_DED_ENABLE_SET", description: "MCAN Double Error Detected Interrupt Enable Set Register", offset: "0xC0", size: "16",
		bits: [
			{ name: "MSGMEM_ENABLE_SET", description: "Message RAM DED Interrupt Pending Enable Set", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_DED_ENABLE_CLR", description: "MCAN Double Error Detected Interrupt Enable Clear Register", offset: "0xE0", size: "16",
		bits: [
			{ name: "MSGMEM_ENABLE_CLR", description: "Message RAM DED Interrupt Pending Enable Clear", size: "1", shift: "0", mask: "0x1" },
		]
	},
	{ name: "ERR_AGGR_ENABLE_SET", description: "MCAN Error Aggregator Enable Set Register", offset: "0x100", size: "16",
		bits: [
			{ name: "ENABLE_PARITY_SET", description: "Enable Parity Errors Set", size: "1", shift: "0", mask: "0x1" },
			{ name: "ENABLE_TIMEOUT_SET", description: "Enable Timeout Errors Set", size: "1", shift: "1", mask: "0x2" },
		]
	},
	{ name: "ERR_AGGR_ENABLE_CLR", description: "MCAN Error Aggregator Enable Clear Register", offset: "0x102", size: "16",
		bits: [
			{ name: "ENABLE_PARITY_CLR", description: "Enable Parity Errors Clear", size: "1", shift: "0", mask: "0x1" },
			{ name: "ENABLE_TIMEOUT_CLR", description: "Enable Timeout Errors Clear", size: "1", shift: "1", mask: "0x2" },
		]
	},
	{ name: "ERR_AGGR_STATUS_SET", description: "MCAN Error Aggregator Status Set Register", offset: "0x104", size: "16",
		bits: [
			{ name: "AGGR_PARITY_ERR", description: "Aggregator Parity Error Status", size: "2", shift: "0", mask: "0x3" },
			{ name: "SVBUS_TIMEOUT", description: "Aggregator Serial VBUS Timeout Error Status", size: "2", shift: "2", mask: "0xC" },
		]
	},
	{ name: "ERR_AGGR_STATUS_CLR", description: "MCAN Error Aggregator Status Clear Register", offset: "0x106", size: "16",
		bits: [
			{ name: "AGGR_PARITY_ERR", description: "Aggregator Parity Error Status", size: "2", shift: "0", mask: "0x3" },
			{ name: "SVBUS_TIMEOUT", description: "Aggregator Serial VBUS Timeout Error Status", size: "2", shift: "2", mask: "0xC" },
		]
	},
];
module.exports = {
	mcanRegisters: MCAN_REGISTERS,
}
