import * as fs from 'fs';
import * as path from 'path';

//
// migrationGuide.ts
//
// Parses a TI "any-to-any" driverlib migration-guide HTML report (the pages served from
// dev.ti.com/tirex .../_Migration_Guides/html_pages/diff_reports/*.html) and renders a single
// section — or the whole report — as Markdown.
//
// The report is generated by Python's difflib, which highlights character-level changes by
// wrapping individual characters in <span> tags; naively stripping tags with a space fragments
// register/identifier tokens. The parser here strips tags with NO substitution so those tokens
// rejoin, and reconstructs function bodies from difflib's per-line `from<fn>_<N>` / `to<fn>_<M>`
// id attributes (the unified "integrated" table), which is complete where the side-by-side one
// collapses added lines.
//
// This module is pure (no vscode dependency) and has no side effects — it only exports
// functions that return the Markdown text.
//

// Decode the entities that appear in these pages (&amp; last to avoid double-decoding).
function unescapeHtml(s: string): string {
	return s
		.replace(/&nbsp;/g, ' ')
		.replace(/&lt;/g, '<')
		.replace(/&gt;/g, '>')
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&#x([0-9a-fA-F]+);/g, (_m, h) => String.fromCodePoint(parseInt(h, 16)))
		.replace(/&#(\d+);/g, (_m, d) => String.fromCodePoint(parseInt(d, 10)))
		.replace(/&amp;/g, '&');
}

// Strip tags with NO substitution so difflib's char-level <span>s rejoin the token.
const clean = (s: string): string => unescapeHtml(s.replace(/<[^>]+>/g, '')).replace(/\s+$/, '');
const oneLine = (s: string): string => clean(s).replace(/\s+/g, ' ').trim();
const fmtList = (s: string): string => s.split(',').map(t => t.trim()).filter(Boolean).join(', ');
const dev = (label: string): string => (label.split('\\').pop() || label).trim();

// Render one section (by its heading anchor id) to Markdown.
function renderSection(html: string, anchor: string, sourceLabel: string, targetLabel: string): string {
	const hOpen = html.indexOf(`<h2 class="body-heading" id="${anchor}"`);
	if (hOpen < 0) { return `## \`${anchor}\`\n\n_ERROR: section not found._`; }
	const rest = html.slice(hOpen + 5);
	const nextH = rest.search(/<h2 class="body-heading" id="/);
	const section = nextH >= 0 ? html.slice(hOpen, hOpen + 5 + nextH) : html.slice(hOpen);

	const gt = section.indexOf('>');
	const aLink = section.indexOf('<a class="anchor-link', gt);
	const headingText = oneLine(section.slice(gt + 1, aLink >= 0 ? aLink : section.indexOf('</h2>')));

	// Notes are the <li> bullets before the first table.
	const preTableEnd = section.indexOf('<table');
	const preTable = preTableEnd >= 0 ? section.slice(0, preTableEnd) : section;
	const notes = [...preTable.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/g)].map(m => oneLine(m[1])).filter(Boolean);

	// Interpret notes into a structured change list + flags.
	type Change = { aspect: string; source: string; target: string };
	const changes: Change[] = [];
	let contentChanged = false;
	let missingIn = '';
	for (let i = 0; i < notes.length; i++) {
		const n = notes[i];
		let m = n.match(/^Function (.+?) does not match\s+(.+?):\s*(.*)$/i);
		if (m) {
			const raw = m[1].toLowerCase().trim();
			const aspect = raw === 'args' ? 'arguments' : raw === 'args types' ? 'argument types' : raw;
			let tgt = '';
			const nx = notes[i + 1];
			if (nx && !/does not match/i.test(nx)) {
				const m2 = nx.match(/^(.+?):\s*(.*)$/);
				if (m2) { tgt = m2[2].trim(); i++; }
			}
			changes.push({ aspect, source: m[3].trim(), target: tgt });
			continue;
		}
		if (/content does not match/i.test(n)) { contentChanged = true; continue; }
		m = n.match(/^Function does not exist in\s+(.+)$/i);
		if (m) { missingIn = m[1].trim(); }
	}

	// Integrated (unified) diff table -> old/new function bodies.
	const parseBodies = (): { oldBody: string; newBody: string; have: boolean } => {
		const id = section.match(/id="difflib_chg_to\d+__top_integrated"/);
		if (!id) { return { oldBody: '', newBody: '', have: false }; }
		const s = section.indexOf(id[0]);
		const table = section.slice(s, section.indexOf('</table>', s));
		const oldL = new Map<number, string>();
		const newL = new Map<number, string>();
		for (const row of table.match(/<tr>[\s\S]*?<\/tr>/g) || []) {
			const f = row.match(/id="from\d+_(\d+)"/);
			const t = row.match(/id="to\d+_(\d+)"/);
			const cc = [...row.matchAll(/<td nowrap="nowrap">([\s\S]*?)<\/td>/g)];
			const code = cc.length ? clean(cc[cc.length - 1][1]) : '';
			if (f) { oldL.set(Number(f[1]), code); }
			if (t) { newL.set(Number(t[1]), code); }
		}
		const asm = (m: Map<number, string>) => [...m.keys()].sort((a, b) => a - b).map(k => m.get(k) as string).join('\n');
		return { oldBody: asm(oldL), newBody: asm(newL), have: oldL.size > 0 || newL.size > 0 };
	};

	// pandas "Styler" difference table (enums / registers) -> Markdown table.
	const renderDiffTable = (): string[] => {
		const t0 = section.indexOf('<table');
		const table = section.slice(t0, section.indexOf('</table>', t0) + 8);
		let headers = [...table.matchAll(/<th[^>]*class="[^"]*col_heading[^"]*"[^>]*>([\s\S]*?)<\/th>/g)].map(m => oneLine(m[1]));
		const tb = table.match(/<tbody>([\s\S]*?)<\/tbody>/);
		const body = tb ? tb[1] : table;
		const rows: string[][] = [];
		for (const r of body.match(/<tr[^>]*>[\s\S]*?<\/tr>/g) || []) {
			const cells = [...r.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/g)].map(m => oneLine(m[1]));
			if (cells.some(c => c)) { rows.push(cells); }
		}
		if (!headers.length && rows.length) { headers = rows.shift() as string[]; }
		const esc = (c: string) => c.replace(/\|/g, '\\|');
		const md = ['| ' + headers.map(esc).join(' | ') + ' |', '| ' + headers.map(() => '---').join(' | ') + ' |'];
		for (const r of rows) { md.push('| ' + headers.map((_, i) => esc(r[i] || '')).join(' | ') + ' |'); }
		return md;
	};

	const out: string[] = [];
	const notesBlock = () => {
		if (notes.length) {
			out.push('', '**Notes:**');
			for (const n of notes) { out.push(`- ${n}`); }
		}
	};

	if (missingIn) {
		const md = dev(missingIn);
		const kind = md === dev(targetLabel) ? `removed — exists only in source (${dev(sourceLabel)})`
			: md === dev(sourceLabel) ? `added — exists only in target (${dev(targetLabel)})`
				: `does not exist in ${missingIn}`;
		out.push(`## \`${anchor}\` — ${kind}`, '', `**Migration:** ${sourceLabel} → ${targetLabel}`);
		notesBlock();
	} else if (section.includes('__top_integrated')) {
		const aspects = new Set(changes.map(c => c.aspect));
		const kinds: string[] = [];
		if (aspects.has('return type')) { kinds.push('return type changed'); }
		if (aspects.has('arguments')) { kinds.push('arguments changed'); }
		if (aspects.has('argument types')) { kinds.push('argument types changed'); }
		if (contentChanged) { kinds.push('content changed'); }
		if (!kinds.length) { kinds.push('changed'); }
		out.push(`## \`${anchor}\` — ${kinds.join(' & ')}`, '', `**Migration:** ${sourceLabel} → ${targetLabel}`);
		if (changes.length) {
			out.push('', '**Changes:**');
			for (const c of changes) { out.push(`- ${c.aspect}: \`${fmtList(c.source)}\` → \`${fmtList(c.target)}\``); }
		}
		notesBlock();
		const { oldBody, newBody, have } = parseBodies();
		if (have) { out.push('', '### Old (source)', '```c', oldBody, '```', '', '### New (target)', '```c', newBody, '```'); }
	} else if (section.includes('<table')) {
		const kind = /_Enums$/i.test(anchor) ? 'enum differences' : /_Registers$/i.test(anchor) ? 'register differences' : 'differences';
		out.push(`## \`${anchor}\` — ${kind}`, '');
		if (headingText) { out.push(`**${headingText}**`); }
		out.push(`**Migration:** ${sourceLabel} → ${targetLabel}`, '', ...renderDiffTable());
	} else {
		out.push(`## \`${anchor}\``, '', `**Migration:** ${sourceLabel} → ${targetLabel}`);
		notesBlock();
	}
	return out.join('\n');
}

/**
 * Render a migration-guide section (or the whole report) to Markdown from the HTML content.
 *
 * @param html   The full HTML of a driverlib migration diff-report page.
 * @param anchor A section heading id (e.g. "CMPSS_configFilterHigh", "adc_Registers"),
 *               or the literal "--all" to render every section into one document.
 * @returns Markdown text.
 */
export function renderMigrationGuideMarkdownFromHtml(html: string, anchor: string): string {
	const titleM = html.match(/<title>Analysis of (.+?) vs (.+?)<\/title>/);
	const sourceLabel = titleM ? titleM[1].trim() : '';
	const targetLabel = titleM ? titleM[2].trim() : '';

	if (anchor === '--all') {
		const anchors = [...html.matchAll(/<h2 class="body-heading" id="([^"]+)"/g)].map(m => m[1]);
		const parts = [`# Migration report — ${sourceLabel} → ${targetLabel}`, `_${anchors.length} sections_`, ''];
		for (const a of anchors) { parts.push(renderSection(html, a, sourceLabel, targetLabel), '\n---\n'); }
		return parts.join('\n');
	}
	return renderSection(html, anchor, sourceLabel, targetLabel);
}

/**
 * Read a migration-guide HTML file from disk and render a section (or the whole report) to Markdown.
 *
 * @param htmlPath Path to a driverlib migration diff-report HTML file.
 * @param anchor   A section heading id, or the literal "--all" for the whole report.
 * @returns Markdown text.
 */
export function renderMigrationGuideMarkdown(htmlPath: string, anchor: string): string {
	const html = fs.readFileSync(path.resolve(htmlPath), 'utf8');
	return renderMigrationGuideMarkdownFromHtml(html, anchor);
}
